import type { Config } from "tailwindcss"

export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
        display: ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
        "headline-lg-mobile": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
        "headline-lg": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
        "headline-md": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
        "title-lg": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
        "body-lg": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
        "body-md": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
        "label-md": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
        "label-sm": ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      colors: {
        background: "#fef7ff",
        surface: "#fef7ff",
        "surface-dim": "#dfd8e2",
        "surface-bright": "#fef7ff",
        "surface-lowest": "#ffffff",
        "surface-low": "#f9f1fb",
        "surface-container": "#f3ebf6",
        "surface-container-low": "#f9f1fb",
        "surface-container-high": "#ede6f0",
        "surface-container-highest": "#e7e0ea",
        "surface-variant": "#e7e0ea",
        "on-surface": "#1d1a21",
        "on-surface-muted": "#4a4452",
        "on-surface-variant": "#4a4452",
        outline: "#7b7483",
        "outline-variant": "#ccc3d4",
        primary: "#6f44b2",
        "primary-container": "#885ecd",
        "primary-fixed": "#ecdcff",
        "primary-fixed-dim": "#d5baff",
        "on-primary": "#ffffff",
        "on-primary-container": "#fffbff",
        "on-primary-fixed": "#270057",
        "on-primary-fixed-variant": "#592c9b",
        secondary: "#a52885",
        "secondary-container": "#fd74d1",
        "secondary-fixed": "#ffd8ec",
        "secondary-fixed-dim": "#ffaedf",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#3b002d",
        "on-secondary-fixed-variant": "#87026b",
        "on-secondary-container": "#73005b",
        tertiary: "#a72d53",
        "tertiary-container": "#c7466b",
        "tertiary-fixed": "#ffd9df",
        "tertiary-fixed-dim": "#ffb1c1",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#3f0017",
        "on-tertiary-fixed-variant": "#8a143e",
        "on-tertiary-container": "#fffbff",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#332f37",
        "inverse-on-surface": "#f6eef8",
        "inverse-primary": "#d5baff",
        "surface-tint": "#7146b5",
        "on-background": "#1d1a21",
        coral: "#ff9971",
        yellow: "#ffc95e",
        lime: "#f9f871",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      boxShadow: {
        ambient: "0px 10px 30px rgba(111, 68, 178, 0.08)",
        card: "0px 16px 48px rgba(111, 68, 178, 0.14)",
        dropdown: "0px 16px 44px rgba(29, 26, 33, 0.12)",
        focus: "0 0 0 4px rgba(111, 68, 178, 0.16)",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        gutter: "24px",
        "container-padding": "40px",
        unit: "4px",
      },
    },
  },
  plugins: [],
} satisfies Config
