export { ProposalCard } from "./ui/proposal-card";
export * from "./ui/status-pill";
export * from "./ui/status-flow";
export { DecisionEffectPreview } from "./ui/decision-effect-preview";
export { VoteTally } from "./ui/vote-tally";
export { DecisionHistory } from "./ui/decision-history";
export { MaterialsViewer } from "./ui/materials-viewer";
export { useMaterialAnnotations } from "./model/material-annotations-store";
export type { MaterialAnnotation } from "./model/material-annotations-store";
export { COVER_PRESETS } from "./model/cover-presets";
export * from "./model/proposal-types";
export type { ActionCheck } from "./model/proposal-actions";
export { checkAction, allowedActions } from "./model/proposal-actions";
export { evaluateBoardTally, type TallyResult } from "./model/board-tally";
