export const APP_ROUTES = {
  admin: {
    dashboard: "/app/admin/dashboard",
    users: "/app/admin/users",
    boardMembers: "/app/admin/board-members",
    taskTypes: "/app/admin/task-types",
    taskRates: "/app/admin/task-rates",
    payroll: "/app/admin/payroll",
    storage: "/app/admin/storage",
    aiService: "/app/admin/ai-service",
    auditLogs: "/app/admin/audit-logs",
    systemHealth: "/app/admin/system-health",
    series: "/app/admin/series",
    notifications: "/app/notifications",
  },
  mangaka: {
    dashboard: "/app/mangaka/dashboard",
    series: "/app/mangaka/series",
    manuscripts: "/app/mangaka/manuscripts",
    chapters: "/app/mangaka/chapters",
    tasks: "/app/mangaka/tasks",
    submissions: "/app/mangaka/submissions",
    comments: "/app/mangaka/comments",
    ranking: "/app/mangaka/ranking",
    payroll: "/app/mangaka/payroll",
    notifications: "/app/notifications",
  },
  assistant: {
    dashboard: "/app/assistant/dashboard",
    tasks: "/app/assistant/tasks",
    submissions: "/app/assistant/submissions",
    revisions: "/app/assistant/revisions",
    earnings: "/app/assistant/earnings",
    notifications: "/app/notifications",
  },
  editor: {
    dashboard: "/app/editor/dashboard",
    series: "/app/editor/series",
    manuscripts: "/app/editor/manuscripts",
    chapters: "/app/editor/chapters",
    pages: "/app/editor/pages",
    comments: "/app/editor/comments",
    tasks: "/app/editor/tasks",
    publication: "/app/editor/publication",
    rankingSupport: "/app/editor/ranking-support",
    notifications: "/app/notifications",
  },
  board: {
    dashboard: "/app/board/dashboard",
    approvals: "/app/board/series-approvals",
    votes: "/app/board/votes",
    ranking: "/app/board/ranking",
    rankingImport: "/app/board/ranking/import",
    atRisk: "/app/board/at-risk",
    decisions: "/app/board/decisions",
    notifications: "/app/notifications",
  },
  shared: {
    notifications: "/app/notifications",
  },
} as const

export type AppRouteKey = keyof typeof APP_ROUTES
export type SubRouteKey<T extends AppRouteKey> = keyof (typeof APP_ROUTES)[T]
