/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReadRouteImport } from './routes/read'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadIndexRouteImport } from './routes/read/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as ReadSlugRouteImport } from './routes/read/$slug'
import { Route as AppTasksRouteImport } from './routes/app/tasks'
import { Route as AppSubmissionsRouteImport } from './routes/app/submissions'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppReviewRouteImport } from './routes/app/review'
import { Route as AppRankingsRouteImport } from './routes/app/rankings'
import { Route as AppPublicationsRouteImport } from './routes/app/publications'
import { Route as AppPayrollRouteImport } from './routes/app/payroll'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppBoardRouteImport } from './routes/app/board'
import { Route as AppAssistantRouteRouteImport } from './routes/app/assistant/route'
import { Route as AppSeriesIndexRouteImport } from './routes/app/series/index'
import { Route as AppBoardIndexRouteImport } from './routes/app/board/index'
import { Route as AppAssistantIndexRouteImport } from './routes/app/assistant/index'
import { Route as ReadSlugChapterRouteImport } from './routes/read/$slug/$chapter'
import { Route as AppSeriesNewRouteImport } from './routes/app/series/new'
import { Route as AppSeriesIdRouteImport } from './routes/app/series/$id'
import { Route as AppEditorSeriesReviewRouteImport } from './routes/app/editor/series-review'
import { Route as AppEditorRankingRiskRouteImport } from './routes/app/editor/ranking-risk'
import { Route as AppEditorProductionProgressRouteImport } from './routes/app/editor/production-progress'
import { Route as AppEditorPageAnnotationRouteImport } from './routes/app/editor/page-annotation'
import { Route as AppEditorManagedSeriesRouteImport } from './routes/app/editor/managed-series'
import { Route as AppEditorFinalReviewsRouteImport } from './routes/app/editor/final-reviews'
import { Route as AppEditorDecisionHistoryRouteImport } from './routes/app/editor/decision-history'
import { Route as AppEditorChapterReviewsRouteImport } from './routes/app/editor/chapter-reviews'
import { Route as AppEditorBoardReportsRouteImport } from './routes/app/editor/board-reports'
import { Route as AppBoardVotingSessionsRouteImport } from './routes/app/board/voting-sessions'
import { Route as AppBoardSeriesReviewRouteImport } from './routes/app/board/series-review'
import { Route as AppBoardReaderVotesRouteImport } from './routes/app/board/reader-votes'
import { Route as AppBoardPublishingScheduleRouteImport } from './routes/app/board/publishing-schedule'
import { Route as AppBoardDecisionHistoryRouteImport } from './routes/app/board/decision-history'
import { Route as AppBoardCancellationReviewRouteImport } from './routes/app/board/cancellation-review'
import { Route as AppAssistantTasksRouteImport } from './routes/app/assistant/tasks'
import { Route as AppAssistantSubmissionsRouteImport } from './routes/app/assistant/submissions'
import { Route as AppAssistantSeriesRouteImport } from './routes/app/assistant/series'
import { Route as AppAssistantNotificationsRouteImport } from './routes/app/assistant/notifications'
import { Route as AppAssistantEarningsRouteImport } from './routes/app/assistant/earnings'
import { Route as AppAssistantDashboardRouteImport } from './routes/app/assistant/dashboard'
import { Route as AppAdminUsersRouteImport } from './routes/app/admin/users'
import { Route as AppAdminUserManagementRouteImport } from './routes/app/admin/user-management'
import { Route as AppAdminTaskRatesRouteImport } from './routes/app/admin/task-rates'
import { Route as AppAdminStorageRouteImport } from './routes/app/admin/storage'
import { Route as AppAdminSettingsRouteImport } from './routes/app/admin/settings'
import { Route as AppAdminRolesRouteImport } from './routes/app/admin/roles'
import { Route as AppAdminPayrollRouteImport } from './routes/app/admin/payroll'
import { Route as AppAdminBoardMembersRouteImport } from './routes/app/admin/board-members'
import { Route as AppAdminAuditLogsRouteImport } from './routes/app/admin/audit-logs'
import { Route as AppSeriesIdIndexRouteImport } from './routes/app/series/$id.index'
import { Route as AppSeriesIdTeamRouteImport } from './routes/app/series/$id.team'
import { Route as AppSeriesIdTasksRouteImport } from './routes/app/series/$id.tasks'
import { Route as AppSeriesIdRevisionsRouteImport } from './routes/app/series/$id.revisions'
import { Route as AppSeriesIdReviewsRouteImport } from './routes/app/series/$id.reviews'
import { Route as AppSeriesIdPublicationRouteImport } from './routes/app/series/$id.publication'
import { Route as AppSeriesIdOverviewRouteImport } from './routes/app/series/$id.overview'
import { Route as AppSeriesIdManuscriptRouteImport } from './routes/app/series/$id.manuscript'
import { Route as AppSeriesIdChaptersRouteImport } from './routes/app/series/$id.chapters'
import { Route as AppSeriesIdActivityRouteImport } from './routes/app/series/$id.activity'
import { Route as AppPagesIdStudioRouteImport } from './routes/app/pages/$id.studio'
import { Route as AppEditorChapterReviewsVersionIdRouteImport } from './routes/app/editor/chapter-reviews/$versionId'
import { Route as AppEditorTasksIdFinalReviewRouteImport } from './routes/app/editor/tasks/$id.final-review'
import { Route as AppEditorSeriesIdReviewRouteImport } from './routes/app/editor/series/$id.review'
import { Route as AppChaptersIdPagesUploadRouteImport } from './routes/app/chapters/$id.pages.upload'
import { Route as AppBoardSeriesIdVoteRouteImport } from './routes/app/board/series/$id.vote'
import { Route as AppAssistantTasksTaskIdStudioRouteImport } from './routes/app/assistant/tasks.$taskId.studio'

const ReadRoute = ReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadIndexRoute = ReadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReadRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ReadSlugRoute = ReadSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ReadRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmissionsRoute = AppSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingsRoute = AppRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AppRoute,
} as any)
const AppPublicationsRoute = AppPublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardRoute = AppBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRouteRoute = AppAssistantRouteRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppSeriesIndexRoute = AppSeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardIndexRoute = AppBoardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBoardRoute,
} as any)
const AppAssistantIndexRoute = AppAssistantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAssistantRouteRoute,
} as any)
const ReadSlugChapterRoute = ReadSlugChapterRouteImport.update({
  id: '/$chapter',
  path: '/$chapter',
  getParentRoute: () => ReadSlugRoute,
} as any)
const AppSeriesNewRoute = AppSeriesNewRouteImport.update({
  id: '/series/new',
  path: '/series/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSeriesIdRoute = AppSeriesIdRouteImport.update({
  id: '/series/$id',
  path: '/series/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorSeriesReviewRoute = AppEditorSeriesReviewRouteImport.update({
  id: '/editor/series-review',
  path: '/editor/series-review',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorRankingRiskRoute = AppEditorRankingRiskRouteImport.update({
  id: '/editor/ranking-risk',
  path: '/editor/ranking-risk',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorProductionProgressRoute =
  AppEditorProductionProgressRouteImport.update({
    id: '/editor/production-progress',
    path: '/editor/production-progress',
    getParentRoute: () => AppRoute,
  } as any)
const AppEditorPageAnnotationRoute = AppEditorPageAnnotationRouteImport.update({
  id: '/editor/page-annotation',
  path: '/editor/page-annotation',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorManagedSeriesRoute = AppEditorManagedSeriesRouteImport.update({
  id: '/editor/managed-series',
  path: '/editor/managed-series',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorFinalReviewsRoute = AppEditorFinalReviewsRouteImport.update({
  id: '/editor/final-reviews',
  path: '/editor/final-reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorDecisionHistoryRoute =
  AppEditorDecisionHistoryRouteImport.update({
    id: '/editor/decision-history',
    path: '/editor/decision-history',
    getParentRoute: () => AppRoute,
  } as any)
const AppEditorChapterReviewsRoute = AppEditorChapterReviewsRouteImport.update({
  id: '/editor/chapter-reviews',
  path: '/editor/chapter-reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorBoardReportsRoute = AppEditorBoardReportsRouteImport.update({
  id: '/editor/board-reports',
  path: '/editor/board-reports',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardVotingSessionsRoute = AppBoardVotingSessionsRouteImport.update({
  id: '/voting-sessions',
  path: '/voting-sessions',
  getParentRoute: () => AppBoardRoute,
} as any)
const AppBoardSeriesReviewRoute = AppBoardSeriesReviewRouteImport.update({
  id: '/series-review',
  path: '/series-review',
  getParentRoute: () => AppBoardRoute,
} as any)
const AppBoardReaderVotesRoute = AppBoardReaderVotesRouteImport.update({
  id: '/reader-votes',
  path: '/reader-votes',
  getParentRoute: () => AppBoardRoute,
} as any)
const AppBoardPublishingScheduleRoute =
  AppBoardPublishingScheduleRouteImport.update({
    id: '/publishing-schedule',
    path: '/publishing-schedule',
    getParentRoute: () => AppBoardRoute,
  } as any)
const AppBoardDecisionHistoryRoute = AppBoardDecisionHistoryRouteImport.update({
  id: '/decision-history',
  path: '/decision-history',
  getParentRoute: () => AppBoardRoute,
} as any)
const AppBoardCancellationReviewRoute =
  AppBoardCancellationReviewRouteImport.update({
    id: '/cancellation-review',
    path: '/cancellation-review',
    getParentRoute: () => AppBoardRoute,
  } as any)
const AppAssistantTasksRoute = AppAssistantTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppAssistantRouteRoute,
} as any)
const AppAssistantSubmissionsRoute = AppAssistantSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppAssistantRouteRoute,
} as any)
const AppAssistantSeriesRoute = AppAssistantSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => AppAssistantRouteRoute,
} as any)
const AppAssistantNotificationsRoute =
  AppAssistantNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppAssistantRouteRoute,
  } as any)
const AppAssistantEarningsRoute = AppAssistantEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AppAssistantRouteRoute,
} as any)
const AppAssistantDashboardRoute = AppAssistantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppAssistantRouteRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUserManagementRoute = AppAdminUserManagementRouteImport.update({
  id: '/admin/user-management',
  path: '/admin/user-management',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTaskRatesRoute = AppAdminTaskRatesRouteImport.update({
  id: '/admin/task-rates',
  path: '/admin/task-rates',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminStorageRoute = AppAdminStorageRouteImport.update({
  id: '/admin/storage',
  path: '/admin/storage',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRolesRoute = AppAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPayrollRoute = AppAdminPayrollRouteImport.update({
  id: '/admin/payroll',
  path: '/admin/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminBoardMembersRoute = AppAdminBoardMembersRouteImport.update({
  id: '/admin/board-members',
  path: '/admin/board-members',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditLogsRoute = AppAdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppSeriesIdIndexRoute = AppSeriesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSeriesIdRoute,
} as any)
const AppSeriesIdTeamRoute = AppSeriesIdTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppSeriesIdRoute,
} as any)
const AppSeriesIdTasksRoute = AppSeriesIdTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppSeriesIdRoute,
} as any)
const AppSeriesIdRevisionsRoute = AppSeriesIdRevisionsRouteImport.update({
  id: '/revisions',
  path: '/revisions',
  getParentRoute: () => AppSeriesIdRoute,
} as any)
const AppSeriesIdReviewsRoute = AppSeriesIdReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppSeriesIdRoute,
} as any)
const AppSeriesIdPublicationRoute = AppSeriesIdPublicationRouteImport.update({
  id: '/publication',
  path: '/publication',
  getParentRoute: () => AppSeriesIdRoute,
} as any)
const AppSeriesIdOverviewRoute = AppSeriesIdOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppSeriesIdRoute,
} as any)
const AppSeriesIdManuscriptRoute = AppSeriesIdManuscriptRouteImport.update({
  id: '/manuscript',
  path: '/manuscript',
  getParentRoute: () => AppSeriesIdRoute,
} as any)
const AppSeriesIdChaptersRoute = AppSeriesIdChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => AppSeriesIdRoute,
} as any)
const AppSeriesIdActivityRoute = AppSeriesIdActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppSeriesIdRoute,
} as any)
const AppPagesIdStudioRoute = AppPagesIdStudioRouteImport.update({
  id: '/pages/$id/studio',
  path: '/pages/$id/studio',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorChapterReviewsVersionIdRoute =
  AppEditorChapterReviewsVersionIdRouteImport.update({
    id: '/$versionId',
    path: '/$versionId',
    getParentRoute: () => AppEditorChapterReviewsRoute,
  } as any)
const AppEditorTasksIdFinalReviewRoute =
  AppEditorTasksIdFinalReviewRouteImport.update({
    id: '/editor/tasks/$id/final-review',
    path: '/editor/tasks/$id/final-review',
    getParentRoute: () => AppRoute,
  } as any)
const AppEditorSeriesIdReviewRoute = AppEditorSeriesIdReviewRouteImport.update({
  id: '/editor/series/$id/review',
  path: '/editor/series/$id/review',
  getParentRoute: () => AppRoute,
} as any)
const AppChaptersIdPagesUploadRoute =
  AppChaptersIdPagesUploadRouteImport.update({
    id: '/chapters/$id/pages/upload',
    path: '/chapters/$id/pages/upload',
    getParentRoute: () => AppRoute,
  } as any)
const AppBoardSeriesIdVoteRoute = AppBoardSeriesIdVoteRouteImport.update({
  id: '/series/$id/vote',
  path: '/series/$id/vote',
  getParentRoute: () => AppBoardRoute,
} as any)
const AppAssistantTasksTaskIdStudioRoute =
  AppAssistantTasksTaskIdStudioRouteImport.update({
    id: '/$taskId/studio',
    path: '/$taskId/studio',
    getParentRoute: () => AppAssistantTasksRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/read': typeof ReadRouteWithChildren
  '/app/assistant': typeof AppAssistantRouteRouteWithChildren
  '/app/board': typeof AppBoardRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/publications': typeof AppPublicationsRoute
  '/app/rankings': typeof AppRankingsRoute
  '/app/review': typeof AppReviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/tasks': typeof AppTasksRoute
  '/read/$slug': typeof ReadSlugRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/read/': typeof ReadIndexRoute
  '/app/admin/audit-logs': typeof AppAdminAuditLogsRoute
  '/app/admin/board-members': typeof AppAdminBoardMembersRoute
  '/app/admin/payroll': typeof AppAdminPayrollRoute
  '/app/admin/roles': typeof AppAdminRolesRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/storage': typeof AppAdminStorageRoute
  '/app/admin/task-rates': typeof AppAdminTaskRatesRoute
  '/app/admin/user-management': typeof AppAdminUserManagementRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/assistant/dashboard': typeof AppAssistantDashboardRoute
  '/app/assistant/earnings': typeof AppAssistantEarningsRoute
  '/app/assistant/notifications': typeof AppAssistantNotificationsRoute
  '/app/assistant/series': typeof AppAssistantSeriesRoute
  '/app/assistant/submissions': typeof AppAssistantSubmissionsRoute
  '/app/assistant/tasks': typeof AppAssistantTasksRouteWithChildren
  '/app/board/cancellation-review': typeof AppBoardCancellationReviewRoute
  '/app/board/decision-history': typeof AppBoardDecisionHistoryRoute
  '/app/board/publishing-schedule': typeof AppBoardPublishingScheduleRoute
  '/app/board/reader-votes': typeof AppBoardReaderVotesRoute
  '/app/board/series-review': typeof AppBoardSeriesReviewRoute
  '/app/board/voting-sessions': typeof AppBoardVotingSessionsRoute
  '/app/editor/board-reports': typeof AppEditorBoardReportsRoute
  '/app/editor/chapter-reviews': typeof AppEditorChapterReviewsRouteWithChildren
  '/app/editor/decision-history': typeof AppEditorDecisionHistoryRoute
  '/app/editor/final-reviews': typeof AppEditorFinalReviewsRoute
  '/app/editor/managed-series': typeof AppEditorManagedSeriesRoute
  '/app/editor/page-annotation': typeof AppEditorPageAnnotationRoute
  '/app/editor/production-progress': typeof AppEditorProductionProgressRoute
  '/app/editor/ranking-risk': typeof AppEditorRankingRiskRoute
  '/app/editor/series-review': typeof AppEditorSeriesReviewRoute
  '/app/series/$id': typeof AppSeriesIdRouteWithChildren
  '/app/series/new': typeof AppSeriesNewRoute
  '/read/$slug/$chapter': typeof ReadSlugChapterRoute
  '/app/assistant/': typeof AppAssistantIndexRoute
  '/app/board/': typeof AppBoardIndexRoute
  '/app/series/': typeof AppSeriesIndexRoute
  '/app/editor/chapter-reviews/$versionId': typeof AppEditorChapterReviewsVersionIdRoute
  '/app/pages/$id/studio': typeof AppPagesIdStudioRoute
  '/app/series/$id/activity': typeof AppSeriesIdActivityRoute
  '/app/series/$id/chapters': typeof AppSeriesIdChaptersRoute
  '/app/series/$id/manuscript': typeof AppSeriesIdManuscriptRoute
  '/app/series/$id/overview': typeof AppSeriesIdOverviewRoute
  '/app/series/$id/publication': typeof AppSeriesIdPublicationRoute
  '/app/series/$id/reviews': typeof AppSeriesIdReviewsRoute
  '/app/series/$id/revisions': typeof AppSeriesIdRevisionsRoute
  '/app/series/$id/tasks': typeof AppSeriesIdTasksRoute
  '/app/series/$id/team': typeof AppSeriesIdTeamRoute
  '/app/series/$id/': typeof AppSeriesIdIndexRoute
  '/app/assistant/tasks/$taskId/studio': typeof AppAssistantTasksTaskIdStudioRoute
  '/app/board/series/$id/vote': typeof AppBoardSeriesIdVoteRoute
  '/app/chapters/$id/pages/upload': typeof AppChaptersIdPagesUploadRoute
  '/app/editor/series/$id/review': typeof AppEditorSeriesIdReviewRoute
  '/app/editor/tasks/$id/final-review': typeof AppEditorTasksIdFinalReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/publications': typeof AppPublicationsRoute
  '/app/rankings': typeof AppRankingsRoute
  '/app/review': typeof AppReviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/tasks': typeof AppTasksRoute
  '/read/$slug': typeof ReadSlugRouteWithChildren
  '/app': typeof AppIndexRoute
  '/read': typeof ReadIndexRoute
  '/app/admin/audit-logs': typeof AppAdminAuditLogsRoute
  '/app/admin/board-members': typeof AppAdminBoardMembersRoute
  '/app/admin/payroll': typeof AppAdminPayrollRoute
  '/app/admin/roles': typeof AppAdminRolesRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/storage': typeof AppAdminStorageRoute
  '/app/admin/task-rates': typeof AppAdminTaskRatesRoute
  '/app/admin/user-management': typeof AppAdminUserManagementRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/assistant/dashboard': typeof AppAssistantDashboardRoute
  '/app/assistant/earnings': typeof AppAssistantEarningsRoute
  '/app/assistant/notifications': typeof AppAssistantNotificationsRoute
  '/app/assistant/series': typeof AppAssistantSeriesRoute
  '/app/assistant/submissions': typeof AppAssistantSubmissionsRoute
  '/app/assistant/tasks': typeof AppAssistantTasksRouteWithChildren
  '/app/board/cancellation-review': typeof AppBoardCancellationReviewRoute
  '/app/board/decision-history': typeof AppBoardDecisionHistoryRoute
  '/app/board/publishing-schedule': typeof AppBoardPublishingScheduleRoute
  '/app/board/reader-votes': typeof AppBoardReaderVotesRoute
  '/app/board/series-review': typeof AppBoardSeriesReviewRoute
  '/app/board/voting-sessions': typeof AppBoardVotingSessionsRoute
  '/app/editor/board-reports': typeof AppEditorBoardReportsRoute
  '/app/editor/chapter-reviews': typeof AppEditorChapterReviewsRouteWithChildren
  '/app/editor/decision-history': typeof AppEditorDecisionHistoryRoute
  '/app/editor/final-reviews': typeof AppEditorFinalReviewsRoute
  '/app/editor/managed-series': typeof AppEditorManagedSeriesRoute
  '/app/editor/page-annotation': typeof AppEditorPageAnnotationRoute
  '/app/editor/production-progress': typeof AppEditorProductionProgressRoute
  '/app/editor/ranking-risk': typeof AppEditorRankingRiskRoute
  '/app/editor/series-review': typeof AppEditorSeriesReviewRoute
  '/app/series/new': typeof AppSeriesNewRoute
  '/read/$slug/$chapter': typeof ReadSlugChapterRoute
  '/app/assistant': typeof AppAssistantIndexRoute
  '/app/board': typeof AppBoardIndexRoute
  '/app/series': typeof AppSeriesIndexRoute
  '/app/editor/chapter-reviews/$versionId': typeof AppEditorChapterReviewsVersionIdRoute
  '/app/pages/$id/studio': typeof AppPagesIdStudioRoute
  '/app/series/$id/activity': typeof AppSeriesIdActivityRoute
  '/app/series/$id/chapters': typeof AppSeriesIdChaptersRoute
  '/app/series/$id/manuscript': typeof AppSeriesIdManuscriptRoute
  '/app/series/$id/overview': typeof AppSeriesIdOverviewRoute
  '/app/series/$id/publication': typeof AppSeriesIdPublicationRoute
  '/app/series/$id/reviews': typeof AppSeriesIdReviewsRoute
  '/app/series/$id/revisions': typeof AppSeriesIdRevisionsRoute
  '/app/series/$id/tasks': typeof AppSeriesIdTasksRoute
  '/app/series/$id/team': typeof AppSeriesIdTeamRoute
  '/app/series/$id': typeof AppSeriesIdIndexRoute
  '/app/assistant/tasks/$taskId/studio': typeof AppAssistantTasksTaskIdStudioRoute
  '/app/board/series/$id/vote': typeof AppBoardSeriesIdVoteRoute
  '/app/chapters/$id/pages/upload': typeof AppChaptersIdPagesUploadRoute
  '/app/editor/series/$id/review': typeof AppEditorSeriesIdReviewRoute
  '/app/editor/tasks/$id/final-review': typeof AppEditorTasksIdFinalReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/read': typeof ReadRouteWithChildren
  '/app/assistant': typeof AppAssistantRouteRouteWithChildren
  '/app/board': typeof AppBoardRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/publications': typeof AppPublicationsRoute
  '/app/rankings': typeof AppRankingsRoute
  '/app/review': typeof AppReviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/tasks': typeof AppTasksRoute
  '/read/$slug': typeof ReadSlugRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/read/': typeof ReadIndexRoute
  '/app/admin/audit-logs': typeof AppAdminAuditLogsRoute
  '/app/admin/board-members': typeof AppAdminBoardMembersRoute
  '/app/admin/payroll': typeof AppAdminPayrollRoute
  '/app/admin/roles': typeof AppAdminRolesRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/storage': typeof AppAdminStorageRoute
  '/app/admin/task-rates': typeof AppAdminTaskRatesRoute
  '/app/admin/user-management': typeof AppAdminUserManagementRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/assistant/dashboard': typeof AppAssistantDashboardRoute
  '/app/assistant/earnings': typeof AppAssistantEarningsRoute
  '/app/assistant/notifications': typeof AppAssistantNotificationsRoute
  '/app/assistant/series': typeof AppAssistantSeriesRoute
  '/app/assistant/submissions': typeof AppAssistantSubmissionsRoute
  '/app/assistant/tasks': typeof AppAssistantTasksRouteWithChildren
  '/app/board/cancellation-review': typeof AppBoardCancellationReviewRoute
  '/app/board/decision-history': typeof AppBoardDecisionHistoryRoute
  '/app/board/publishing-schedule': typeof AppBoardPublishingScheduleRoute
  '/app/board/reader-votes': typeof AppBoardReaderVotesRoute
  '/app/board/series-review': typeof AppBoardSeriesReviewRoute
  '/app/board/voting-sessions': typeof AppBoardVotingSessionsRoute
  '/app/editor/board-reports': typeof AppEditorBoardReportsRoute
  '/app/editor/chapter-reviews': typeof AppEditorChapterReviewsRouteWithChildren
  '/app/editor/decision-history': typeof AppEditorDecisionHistoryRoute
  '/app/editor/final-reviews': typeof AppEditorFinalReviewsRoute
  '/app/editor/managed-series': typeof AppEditorManagedSeriesRoute
  '/app/editor/page-annotation': typeof AppEditorPageAnnotationRoute
  '/app/editor/production-progress': typeof AppEditorProductionProgressRoute
  '/app/editor/ranking-risk': typeof AppEditorRankingRiskRoute
  '/app/editor/series-review': typeof AppEditorSeriesReviewRoute
  '/app/series/$id': typeof AppSeriesIdRouteWithChildren
  '/app/series/new': typeof AppSeriesNewRoute
  '/read/$slug/$chapter': typeof ReadSlugChapterRoute
  '/app/assistant/': typeof AppAssistantIndexRoute
  '/app/board/': typeof AppBoardIndexRoute
  '/app/series/': typeof AppSeriesIndexRoute
  '/app/editor/chapter-reviews/$versionId': typeof AppEditorChapterReviewsVersionIdRoute
  '/app/pages/$id/studio': typeof AppPagesIdStudioRoute
  '/app/series/$id/activity': typeof AppSeriesIdActivityRoute
  '/app/series/$id/chapters': typeof AppSeriesIdChaptersRoute
  '/app/series/$id/manuscript': typeof AppSeriesIdManuscriptRoute
  '/app/series/$id/overview': typeof AppSeriesIdOverviewRoute
  '/app/series/$id/publication': typeof AppSeriesIdPublicationRoute
  '/app/series/$id/reviews': typeof AppSeriesIdReviewsRoute
  '/app/series/$id/revisions': typeof AppSeriesIdRevisionsRoute
  '/app/series/$id/tasks': typeof AppSeriesIdTasksRoute
  '/app/series/$id/team': typeof AppSeriesIdTeamRoute
  '/app/series/$id/': typeof AppSeriesIdIndexRoute
  '/app/assistant/tasks/$taskId/studio': typeof AppAssistantTasksTaskIdStudioRoute
  '/app/board/series/$id/vote': typeof AppBoardSeriesIdVoteRoute
  '/app/chapters/$id/pages/upload': typeof AppChaptersIdPagesUploadRoute
  '/app/editor/series/$id/review': typeof AppEditorSeriesIdReviewRoute
  '/app/editor/tasks/$id/final-review': typeof AppEditorTasksIdFinalReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/read'
    | '/app/assistant'
    | '/app/board'
    | '/app/dashboard'
    | '/app/notifications'
    | '/app/payroll'
    | '/app/publications'
    | '/app/rankings'
    | '/app/review'
    | '/app/settings'
    | '/app/submissions'
    | '/app/tasks'
    | '/read/$slug'
    | '/app/'
    | '/read/'
    | '/app/admin/audit-logs'
    | '/app/admin/board-members'
    | '/app/admin/payroll'
    | '/app/admin/roles'
    | '/app/admin/settings'
    | '/app/admin/storage'
    | '/app/admin/task-rates'
    | '/app/admin/user-management'
    | '/app/admin/users'
    | '/app/assistant/dashboard'
    | '/app/assistant/earnings'
    | '/app/assistant/notifications'
    | '/app/assistant/series'
    | '/app/assistant/submissions'
    | '/app/assistant/tasks'
    | '/app/board/cancellation-review'
    | '/app/board/decision-history'
    | '/app/board/publishing-schedule'
    | '/app/board/reader-votes'
    | '/app/board/series-review'
    | '/app/board/voting-sessions'
    | '/app/editor/board-reports'
    | '/app/editor/chapter-reviews'
    | '/app/editor/decision-history'
    | '/app/editor/final-reviews'
    | '/app/editor/managed-series'
    | '/app/editor/page-annotation'
    | '/app/editor/production-progress'
    | '/app/editor/ranking-risk'
    | '/app/editor/series-review'
    | '/app/series/$id'
    | '/app/series/new'
    | '/read/$slug/$chapter'
    | '/app/assistant/'
    | '/app/board/'
    | '/app/series/'
    | '/app/editor/chapter-reviews/$versionId'
    | '/app/pages/$id/studio'
    | '/app/series/$id/activity'
    | '/app/series/$id/chapters'
    | '/app/series/$id/manuscript'
    | '/app/series/$id/overview'
    | '/app/series/$id/publication'
    | '/app/series/$id/reviews'
    | '/app/series/$id/revisions'
    | '/app/series/$id/tasks'
    | '/app/series/$id/team'
    | '/app/series/$id/'
    | '/app/assistant/tasks/$taskId/studio'
    | '/app/board/series/$id/vote'
    | '/app/chapters/$id/pages/upload'
    | '/app/editor/series/$id/review'
    | '/app/editor/tasks/$id/final-review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/dashboard'
    | '/app/notifications'
    | '/app/payroll'
    | '/app/publications'
    | '/app/rankings'
    | '/app/review'
    | '/app/settings'
    | '/app/submissions'
    | '/app/tasks'
    | '/read/$slug'
    | '/app'
    | '/read'
    | '/app/admin/audit-logs'
    | '/app/admin/board-members'
    | '/app/admin/payroll'
    | '/app/admin/roles'
    | '/app/admin/settings'
    | '/app/admin/storage'
    | '/app/admin/task-rates'
    | '/app/admin/user-management'
    | '/app/admin/users'
    | '/app/assistant/dashboard'
    | '/app/assistant/earnings'
    | '/app/assistant/notifications'
    | '/app/assistant/series'
    | '/app/assistant/submissions'
    | '/app/assistant/tasks'
    | '/app/board/cancellation-review'
    | '/app/board/decision-history'
    | '/app/board/publishing-schedule'
    | '/app/board/reader-votes'
    | '/app/board/series-review'
    | '/app/board/voting-sessions'
    | '/app/editor/board-reports'
    | '/app/editor/chapter-reviews'
    | '/app/editor/decision-history'
    | '/app/editor/final-reviews'
    | '/app/editor/managed-series'
    | '/app/editor/page-annotation'
    | '/app/editor/production-progress'
    | '/app/editor/ranking-risk'
    | '/app/editor/series-review'
    | '/app/series/new'
    | '/read/$slug/$chapter'
    | '/app/assistant'
    | '/app/board'
    | '/app/series'
    | '/app/editor/chapter-reviews/$versionId'
    | '/app/pages/$id/studio'
    | '/app/series/$id/activity'
    | '/app/series/$id/chapters'
    | '/app/series/$id/manuscript'
    | '/app/series/$id/overview'
    | '/app/series/$id/publication'
    | '/app/series/$id/reviews'
    | '/app/series/$id/revisions'
    | '/app/series/$id/tasks'
    | '/app/series/$id/team'
    | '/app/series/$id'
    | '/app/assistant/tasks/$taskId/studio'
    | '/app/board/series/$id/vote'
    | '/app/chapters/$id/pages/upload'
    | '/app/editor/series/$id/review'
    | '/app/editor/tasks/$id/final-review'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/read'
    | '/app/assistant'
    | '/app/board'
    | '/app/dashboard'
    | '/app/notifications'
    | '/app/payroll'
    | '/app/publications'
    | '/app/rankings'
    | '/app/review'
    | '/app/settings'
    | '/app/submissions'
    | '/app/tasks'
    | '/read/$slug'
    | '/app/'
    | '/read/'
    | '/app/admin/audit-logs'
    | '/app/admin/board-members'
    | '/app/admin/payroll'
    | '/app/admin/roles'
    | '/app/admin/settings'
    | '/app/admin/storage'
    | '/app/admin/task-rates'
    | '/app/admin/user-management'
    | '/app/admin/users'
    | '/app/assistant/dashboard'
    | '/app/assistant/earnings'
    | '/app/assistant/notifications'
    | '/app/assistant/series'
    | '/app/assistant/submissions'
    | '/app/assistant/tasks'
    | '/app/board/cancellation-review'
    | '/app/board/decision-history'
    | '/app/board/publishing-schedule'
    | '/app/board/reader-votes'
    | '/app/board/series-review'
    | '/app/board/voting-sessions'
    | '/app/editor/board-reports'
    | '/app/editor/chapter-reviews'
    | '/app/editor/decision-history'
    | '/app/editor/final-reviews'
    | '/app/editor/managed-series'
    | '/app/editor/page-annotation'
    | '/app/editor/production-progress'
    | '/app/editor/ranking-risk'
    | '/app/editor/series-review'
    | '/app/series/$id'
    | '/app/series/new'
    | '/read/$slug/$chapter'
    | '/app/assistant/'
    | '/app/board/'
    | '/app/series/'
    | '/app/editor/chapter-reviews/$versionId'
    | '/app/pages/$id/studio'
    | '/app/series/$id/activity'
    | '/app/series/$id/chapters'
    | '/app/series/$id/manuscript'
    | '/app/series/$id/overview'
    | '/app/series/$id/publication'
    | '/app/series/$id/reviews'
    | '/app/series/$id/revisions'
    | '/app/series/$id/tasks'
    | '/app/series/$id/team'
    | '/app/series/$id/'
    | '/app/assistant/tasks/$taskId/studio'
    | '/app/board/series/$id/vote'
    | '/app/chapters/$id/pages/upload'
    | '/app/editor/series/$id/review'
    | '/app/editor/tasks/$id/final-review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ReadRoute: typeof ReadRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/read': {
      id: '/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof ReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/': {
      id: '/read/'
      path: '/'
      fullPath: '/read/'
      preLoaderRoute: typeof ReadIndexRouteImport
      parentRoute: typeof ReadRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/read/$slug': {
      id: '/read/$slug'
      path: '/$slug'
      fullPath: '/read/$slug'
      preLoaderRoute: typeof ReadSlugRouteImport
      parentRoute: typeof ReadRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/submissions': {
      id: '/app/submissions'
      path: '/submissions'
      fullPath: '/app/submissions'
      preLoaderRoute: typeof AppSubmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review': {
      id: '/app/review'
      path: '/review'
      fullPath: '/app/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rankings': {
      id: '/app/rankings'
      path: '/rankings'
      fullPath: '/app/rankings'
      preLoaderRoute: typeof AppRankingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/publications': {
      id: '/app/publications'
      path: '/publications'
      fullPath: '/app/publications'
      preLoaderRoute: typeof AppPublicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payroll': {
      id: '/app/payroll'
      path: '/payroll'
      fullPath: '/app/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/board': {
      id: '/app/board'
      path: '/board'
      fullPath: '/app/board'
      preLoaderRoute: typeof AppBoardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/series/': {
      id: '/app/series/'
      path: '/series'
      fullPath: '/app/series/'
      preLoaderRoute: typeof AppSeriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/board/': {
      id: '/app/board/'
      path: '/'
      fullPath: '/app/board/'
      preLoaderRoute: typeof AppBoardIndexRouteImport
      parentRoute: typeof AppBoardRoute
    }
    '/app/assistant/': {
      id: '/app/assistant/'
      path: '/'
      fullPath: '/app/assistant/'
      preLoaderRoute: typeof AppAssistantIndexRouteImport
      parentRoute: typeof AppAssistantRouteRoute
    }
    '/read/$slug/$chapter': {
      id: '/read/$slug/$chapter'
      path: '/$chapter'
      fullPath: '/read/$slug/$chapter'
      preLoaderRoute: typeof ReadSlugChapterRouteImport
      parentRoute: typeof ReadSlugRoute
    }
    '/app/series/new': {
      id: '/app/series/new'
      path: '/series/new'
      fullPath: '/app/series/new'
      preLoaderRoute: typeof AppSeriesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/series/$id': {
      id: '/app/series/$id'
      path: '/series/$id'
      fullPath: '/app/series/$id'
      preLoaderRoute: typeof AppSeriesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editor/series-review': {
      id: '/app/editor/series-review'
      path: '/editor/series-review'
      fullPath: '/app/editor/series-review'
      preLoaderRoute: typeof AppEditorSeriesReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editor/ranking-risk': {
      id: '/app/editor/ranking-risk'
      path: '/editor/ranking-risk'
      fullPath: '/app/editor/ranking-risk'
      preLoaderRoute: typeof AppEditorRankingRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editor/production-progress': {
      id: '/app/editor/production-progress'
      path: '/editor/production-progress'
      fullPath: '/app/editor/production-progress'
      preLoaderRoute: typeof AppEditorProductionProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editor/page-annotation': {
      id: '/app/editor/page-annotation'
      path: '/editor/page-annotation'
      fullPath: '/app/editor/page-annotation'
      preLoaderRoute: typeof AppEditorPageAnnotationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editor/managed-series': {
      id: '/app/editor/managed-series'
      path: '/editor/managed-series'
      fullPath: '/app/editor/managed-series'
      preLoaderRoute: typeof AppEditorManagedSeriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editor/final-reviews': {
      id: '/app/editor/final-reviews'
      path: '/editor/final-reviews'
      fullPath: '/app/editor/final-reviews'
      preLoaderRoute: typeof AppEditorFinalReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editor/decision-history': {
      id: '/app/editor/decision-history'
      path: '/editor/decision-history'
      fullPath: '/app/editor/decision-history'
      preLoaderRoute: typeof AppEditorDecisionHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editor/chapter-reviews': {
      id: '/app/editor/chapter-reviews'
      path: '/editor/chapter-reviews'
      fullPath: '/app/editor/chapter-reviews'
      preLoaderRoute: typeof AppEditorChapterReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editor/board-reports': {
      id: '/app/editor/board-reports'
      path: '/editor/board-reports'
      fullPath: '/app/editor/board-reports'
      preLoaderRoute: typeof AppEditorBoardReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/board/voting-sessions': {
      id: '/app/board/voting-sessions'
      path: '/voting-sessions'
      fullPath: '/app/board/voting-sessions'
      preLoaderRoute: typeof AppBoardVotingSessionsRouteImport
      parentRoute: typeof AppBoardRoute
    }
    '/app/board/series-review': {
      id: '/app/board/series-review'
      path: '/series-review'
      fullPath: '/app/board/series-review'
      preLoaderRoute: typeof AppBoardSeriesReviewRouteImport
      parentRoute: typeof AppBoardRoute
    }
    '/app/board/reader-votes': {
      id: '/app/board/reader-votes'
      path: '/reader-votes'
      fullPath: '/app/board/reader-votes'
      preLoaderRoute: typeof AppBoardReaderVotesRouteImport
      parentRoute: typeof AppBoardRoute
    }
    '/app/board/publishing-schedule': {
      id: '/app/board/publishing-schedule'
      path: '/publishing-schedule'
      fullPath: '/app/board/publishing-schedule'
      preLoaderRoute: typeof AppBoardPublishingScheduleRouteImport
      parentRoute: typeof AppBoardRoute
    }
    '/app/board/decision-history': {
      id: '/app/board/decision-history'
      path: '/decision-history'
      fullPath: '/app/board/decision-history'
      preLoaderRoute: typeof AppBoardDecisionHistoryRouteImport
      parentRoute: typeof AppBoardRoute
    }
    '/app/board/cancellation-review': {
      id: '/app/board/cancellation-review'
      path: '/cancellation-review'
      fullPath: '/app/board/cancellation-review'
      preLoaderRoute: typeof AppBoardCancellationReviewRouteImport
      parentRoute: typeof AppBoardRoute
    }
    '/app/assistant/tasks': {
      id: '/app/assistant/tasks'
      path: '/tasks'
      fullPath: '/app/assistant/tasks'
      preLoaderRoute: typeof AppAssistantTasksRouteImport
      parentRoute: typeof AppAssistantRouteRoute
    }
    '/app/assistant/submissions': {
      id: '/app/assistant/submissions'
      path: '/submissions'
      fullPath: '/app/assistant/submissions'
      preLoaderRoute: typeof AppAssistantSubmissionsRouteImport
      parentRoute: typeof AppAssistantRouteRoute
    }
    '/app/assistant/series': {
      id: '/app/assistant/series'
      path: '/series'
      fullPath: '/app/assistant/series'
      preLoaderRoute: typeof AppAssistantSeriesRouteImport
      parentRoute: typeof AppAssistantRouteRoute
    }
    '/app/assistant/notifications': {
      id: '/app/assistant/notifications'
      path: '/notifications'
      fullPath: '/app/assistant/notifications'
      preLoaderRoute: typeof AppAssistantNotificationsRouteImport
      parentRoute: typeof AppAssistantRouteRoute
    }
    '/app/assistant/earnings': {
      id: '/app/assistant/earnings'
      path: '/earnings'
      fullPath: '/app/assistant/earnings'
      preLoaderRoute: typeof AppAssistantEarningsRouteImport
      parentRoute: typeof AppAssistantRouteRoute
    }
    '/app/assistant/dashboard': {
      id: '/app/assistant/dashboard'
      path: '/dashboard'
      fullPath: '/app/assistant/dashboard'
      preLoaderRoute: typeof AppAssistantDashboardRouteImport
      parentRoute: typeof AppAssistantRouteRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/user-management': {
      id: '/app/admin/user-management'
      path: '/admin/user-management'
      fullPath: '/app/admin/user-management'
      preLoaderRoute: typeof AppAdminUserManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/task-rates': {
      id: '/app/admin/task-rates'
      path: '/admin/task-rates'
      fullPath: '/app/admin/task-rates'
      preLoaderRoute: typeof AppAdminTaskRatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/storage': {
      id: '/app/admin/storage'
      path: '/admin/storage'
      fullPath: '/app/admin/storage'
      preLoaderRoute: typeof AppAdminStorageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/settings': {
      id: '/app/admin/settings'
      path: '/admin/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/roles': {
      id: '/app/admin/roles'
      path: '/admin/roles'
      fullPath: '/app/admin/roles'
      preLoaderRoute: typeof AppAdminRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/payroll': {
      id: '/app/admin/payroll'
      path: '/admin/payroll'
      fullPath: '/app/admin/payroll'
      preLoaderRoute: typeof AppAdminPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/board-members': {
      id: '/app/admin/board-members'
      path: '/admin/board-members'
      fullPath: '/app/admin/board-members'
      preLoaderRoute: typeof AppAdminBoardMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/audit-logs': {
      id: '/app/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/app/admin/audit-logs'
      preLoaderRoute: typeof AppAdminAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/series/$id/': {
      id: '/app/series/$id/'
      path: '/'
      fullPath: '/app/series/$id/'
      preLoaderRoute: typeof AppSeriesIdIndexRouteImport
      parentRoute: typeof AppSeriesIdRoute
    }
    '/app/series/$id/team': {
      id: '/app/series/$id/team'
      path: '/team'
      fullPath: '/app/series/$id/team'
      preLoaderRoute: typeof AppSeriesIdTeamRouteImport
      parentRoute: typeof AppSeriesIdRoute
    }
    '/app/series/$id/tasks': {
      id: '/app/series/$id/tasks'
      path: '/tasks'
      fullPath: '/app/series/$id/tasks'
      preLoaderRoute: typeof AppSeriesIdTasksRouteImport
      parentRoute: typeof AppSeriesIdRoute
    }
    '/app/series/$id/revisions': {
      id: '/app/series/$id/revisions'
      path: '/revisions'
      fullPath: '/app/series/$id/revisions'
      preLoaderRoute: typeof AppSeriesIdRevisionsRouteImport
      parentRoute: typeof AppSeriesIdRoute
    }
    '/app/series/$id/reviews': {
      id: '/app/series/$id/reviews'
      path: '/reviews'
      fullPath: '/app/series/$id/reviews'
      preLoaderRoute: typeof AppSeriesIdReviewsRouteImport
      parentRoute: typeof AppSeriesIdRoute
    }
    '/app/series/$id/publication': {
      id: '/app/series/$id/publication'
      path: '/publication'
      fullPath: '/app/series/$id/publication'
      preLoaderRoute: typeof AppSeriesIdPublicationRouteImport
      parentRoute: typeof AppSeriesIdRoute
    }
    '/app/series/$id/overview': {
      id: '/app/series/$id/overview'
      path: '/overview'
      fullPath: '/app/series/$id/overview'
      preLoaderRoute: typeof AppSeriesIdOverviewRouteImport
      parentRoute: typeof AppSeriesIdRoute
    }
    '/app/series/$id/manuscript': {
      id: '/app/series/$id/manuscript'
      path: '/manuscript'
      fullPath: '/app/series/$id/manuscript'
      preLoaderRoute: typeof AppSeriesIdManuscriptRouteImport
      parentRoute: typeof AppSeriesIdRoute
    }
    '/app/series/$id/chapters': {
      id: '/app/series/$id/chapters'
      path: '/chapters'
      fullPath: '/app/series/$id/chapters'
      preLoaderRoute: typeof AppSeriesIdChaptersRouteImport
      parentRoute: typeof AppSeriesIdRoute
    }
    '/app/series/$id/activity': {
      id: '/app/series/$id/activity'
      path: '/activity'
      fullPath: '/app/series/$id/activity'
      preLoaderRoute: typeof AppSeriesIdActivityRouteImport
      parentRoute: typeof AppSeriesIdRoute
    }
    '/app/pages/$id/studio': {
      id: '/app/pages/$id/studio'
      path: '/pages/$id/studio'
      fullPath: '/app/pages/$id/studio'
      preLoaderRoute: typeof AppPagesIdStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editor/chapter-reviews/$versionId': {
      id: '/app/editor/chapter-reviews/$versionId'
      path: '/$versionId'
      fullPath: '/app/editor/chapter-reviews/$versionId'
      preLoaderRoute: typeof AppEditorChapterReviewsVersionIdRouteImport
      parentRoute: typeof AppEditorChapterReviewsRoute
    }
    '/app/editor/tasks/$id/final-review': {
      id: '/app/editor/tasks/$id/final-review'
      path: '/editor/tasks/$id/final-review'
      fullPath: '/app/editor/tasks/$id/final-review'
      preLoaderRoute: typeof AppEditorTasksIdFinalReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editor/series/$id/review': {
      id: '/app/editor/series/$id/review'
      path: '/editor/series/$id/review'
      fullPath: '/app/editor/series/$id/review'
      preLoaderRoute: typeof AppEditorSeriesIdReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chapters/$id/pages/upload': {
      id: '/app/chapters/$id/pages/upload'
      path: '/chapters/$id/pages/upload'
      fullPath: '/app/chapters/$id/pages/upload'
      preLoaderRoute: typeof AppChaptersIdPagesUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/board/series/$id/vote': {
      id: '/app/board/series/$id/vote'
      path: '/series/$id/vote'
      fullPath: '/app/board/series/$id/vote'
      preLoaderRoute: typeof AppBoardSeriesIdVoteRouteImport
      parentRoute: typeof AppBoardRoute
    }
    '/app/assistant/tasks/$taskId/studio': {
      id: '/app/assistant/tasks/$taskId/studio'
      path: '/$taskId/studio'
      fullPath: '/app/assistant/tasks/$taskId/studio'
      preLoaderRoute: typeof AppAssistantTasksTaskIdStudioRouteImport
      parentRoute: typeof AppAssistantTasksRoute
    }
  }
}

interface AppAssistantTasksRouteChildren {
  AppAssistantTasksTaskIdStudioRoute: typeof AppAssistantTasksTaskIdStudioRoute
}

const AppAssistantTasksRouteChildren: AppAssistantTasksRouteChildren = {
  AppAssistantTasksTaskIdStudioRoute: AppAssistantTasksTaskIdStudioRoute,
}

const AppAssistantTasksRouteWithChildren =
  AppAssistantTasksRoute._addFileChildren(AppAssistantTasksRouteChildren)

interface AppAssistantRouteRouteChildren {
  AppAssistantDashboardRoute: typeof AppAssistantDashboardRoute
  AppAssistantEarningsRoute: typeof AppAssistantEarningsRoute
  AppAssistantNotificationsRoute: typeof AppAssistantNotificationsRoute
  AppAssistantSeriesRoute: typeof AppAssistantSeriesRoute
  AppAssistantSubmissionsRoute: typeof AppAssistantSubmissionsRoute
  AppAssistantTasksRoute: typeof AppAssistantTasksRouteWithChildren
  AppAssistantIndexRoute: typeof AppAssistantIndexRoute
}

const AppAssistantRouteRouteChildren: AppAssistantRouteRouteChildren = {
  AppAssistantDashboardRoute: AppAssistantDashboardRoute,
  AppAssistantEarningsRoute: AppAssistantEarningsRoute,
  AppAssistantNotificationsRoute: AppAssistantNotificationsRoute,
  AppAssistantSeriesRoute: AppAssistantSeriesRoute,
  AppAssistantSubmissionsRoute: AppAssistantSubmissionsRoute,
  AppAssistantTasksRoute: AppAssistantTasksRouteWithChildren,
  AppAssistantIndexRoute: AppAssistantIndexRoute,
}

const AppAssistantRouteRouteWithChildren =
  AppAssistantRouteRoute._addFileChildren(AppAssistantRouteRouteChildren)

interface AppBoardRouteChildren {
  AppBoardCancellationReviewRoute: typeof AppBoardCancellationReviewRoute
  AppBoardDecisionHistoryRoute: typeof AppBoardDecisionHistoryRoute
  AppBoardPublishingScheduleRoute: typeof AppBoardPublishingScheduleRoute
  AppBoardReaderVotesRoute: typeof AppBoardReaderVotesRoute
  AppBoardSeriesReviewRoute: typeof AppBoardSeriesReviewRoute
  AppBoardVotingSessionsRoute: typeof AppBoardVotingSessionsRoute
  AppBoardIndexRoute: typeof AppBoardIndexRoute
  AppBoardSeriesIdVoteRoute: typeof AppBoardSeriesIdVoteRoute
}

const AppBoardRouteChildren: AppBoardRouteChildren = {
  AppBoardCancellationReviewRoute: AppBoardCancellationReviewRoute,
  AppBoardDecisionHistoryRoute: AppBoardDecisionHistoryRoute,
  AppBoardPublishingScheduleRoute: AppBoardPublishingScheduleRoute,
  AppBoardReaderVotesRoute: AppBoardReaderVotesRoute,
  AppBoardSeriesReviewRoute: AppBoardSeriesReviewRoute,
  AppBoardVotingSessionsRoute: AppBoardVotingSessionsRoute,
  AppBoardIndexRoute: AppBoardIndexRoute,
  AppBoardSeriesIdVoteRoute: AppBoardSeriesIdVoteRoute,
}

const AppBoardRouteWithChildren = AppBoardRoute._addFileChildren(
  AppBoardRouteChildren,
)

interface AppEditorChapterReviewsRouteChildren {
  AppEditorChapterReviewsVersionIdRoute: typeof AppEditorChapterReviewsVersionIdRoute
}

const AppEditorChapterReviewsRouteChildren: AppEditorChapterReviewsRouteChildren =
  {
    AppEditorChapterReviewsVersionIdRoute:
      AppEditorChapterReviewsVersionIdRoute,
  }

const AppEditorChapterReviewsRouteWithChildren =
  AppEditorChapterReviewsRoute._addFileChildren(
    AppEditorChapterReviewsRouteChildren,
  )

interface AppSeriesIdRouteChildren {
  AppSeriesIdActivityRoute: typeof AppSeriesIdActivityRoute
  AppSeriesIdChaptersRoute: typeof AppSeriesIdChaptersRoute
  AppSeriesIdManuscriptRoute: typeof AppSeriesIdManuscriptRoute
  AppSeriesIdOverviewRoute: typeof AppSeriesIdOverviewRoute
  AppSeriesIdPublicationRoute: typeof AppSeriesIdPublicationRoute
  AppSeriesIdReviewsRoute: typeof AppSeriesIdReviewsRoute
  AppSeriesIdRevisionsRoute: typeof AppSeriesIdRevisionsRoute
  AppSeriesIdTasksRoute: typeof AppSeriesIdTasksRoute
  AppSeriesIdTeamRoute: typeof AppSeriesIdTeamRoute
  AppSeriesIdIndexRoute: typeof AppSeriesIdIndexRoute
}

const AppSeriesIdRouteChildren: AppSeriesIdRouteChildren = {
  AppSeriesIdActivityRoute: AppSeriesIdActivityRoute,
  AppSeriesIdChaptersRoute: AppSeriesIdChaptersRoute,
  AppSeriesIdManuscriptRoute: AppSeriesIdManuscriptRoute,
  AppSeriesIdOverviewRoute: AppSeriesIdOverviewRoute,
  AppSeriesIdPublicationRoute: AppSeriesIdPublicationRoute,
  AppSeriesIdReviewsRoute: AppSeriesIdReviewsRoute,
  AppSeriesIdRevisionsRoute: AppSeriesIdRevisionsRoute,
  AppSeriesIdTasksRoute: AppSeriesIdTasksRoute,
  AppSeriesIdTeamRoute: AppSeriesIdTeamRoute,
  AppSeriesIdIndexRoute: AppSeriesIdIndexRoute,
}

const AppSeriesIdRouteWithChildren = AppSeriesIdRoute._addFileChildren(
  AppSeriesIdRouteChildren,
)

interface AppRouteChildren {
  AppAssistantRouteRoute: typeof AppAssistantRouteRouteWithChildren
  AppBoardRoute: typeof AppBoardRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppPublicationsRoute: typeof AppPublicationsRoute
  AppRankingsRoute: typeof AppRankingsRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubmissionsRoute: typeof AppSubmissionsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminAuditLogsRoute: typeof AppAdminAuditLogsRoute
  AppAdminBoardMembersRoute: typeof AppAdminBoardMembersRoute
  AppAdminPayrollRoute: typeof AppAdminPayrollRoute
  AppAdminRolesRoute: typeof AppAdminRolesRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminStorageRoute: typeof AppAdminStorageRoute
  AppAdminTaskRatesRoute: typeof AppAdminTaskRatesRoute
  AppAdminUserManagementRoute: typeof AppAdminUserManagementRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppEditorBoardReportsRoute: typeof AppEditorBoardReportsRoute
  AppEditorChapterReviewsRoute: typeof AppEditorChapterReviewsRouteWithChildren
  AppEditorDecisionHistoryRoute: typeof AppEditorDecisionHistoryRoute
  AppEditorFinalReviewsRoute: typeof AppEditorFinalReviewsRoute
  AppEditorManagedSeriesRoute: typeof AppEditorManagedSeriesRoute
  AppEditorPageAnnotationRoute: typeof AppEditorPageAnnotationRoute
  AppEditorProductionProgressRoute: typeof AppEditorProductionProgressRoute
  AppEditorRankingRiskRoute: typeof AppEditorRankingRiskRoute
  AppEditorSeriesReviewRoute: typeof AppEditorSeriesReviewRoute
  AppSeriesIdRoute: typeof AppSeriesIdRouteWithChildren
  AppSeriesNewRoute: typeof AppSeriesNewRoute
  AppSeriesIndexRoute: typeof AppSeriesIndexRoute
  AppPagesIdStudioRoute: typeof AppPagesIdStudioRoute
  AppChaptersIdPagesUploadRoute: typeof AppChaptersIdPagesUploadRoute
  AppEditorSeriesIdReviewRoute: typeof AppEditorSeriesIdReviewRoute
  AppEditorTasksIdFinalReviewRoute: typeof AppEditorTasksIdFinalReviewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistantRouteRoute: AppAssistantRouteRouteWithChildren,
  AppBoardRoute: AppBoardRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppPublicationsRoute: AppPublicationsRoute,
  AppRankingsRoute: AppRankingsRoute,
  AppReviewRoute: AppReviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubmissionsRoute: AppSubmissionsRoute,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminAuditLogsRoute: AppAdminAuditLogsRoute,
  AppAdminBoardMembersRoute: AppAdminBoardMembersRoute,
  AppAdminPayrollRoute: AppAdminPayrollRoute,
  AppAdminRolesRoute: AppAdminRolesRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminStorageRoute: AppAdminStorageRoute,
  AppAdminTaskRatesRoute: AppAdminTaskRatesRoute,
  AppAdminUserManagementRoute: AppAdminUserManagementRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppEditorBoardReportsRoute: AppEditorBoardReportsRoute,
  AppEditorChapterReviewsRoute: AppEditorChapterReviewsRouteWithChildren,
  AppEditorDecisionHistoryRoute: AppEditorDecisionHistoryRoute,
  AppEditorFinalReviewsRoute: AppEditorFinalReviewsRoute,
  AppEditorManagedSeriesRoute: AppEditorManagedSeriesRoute,
  AppEditorPageAnnotationRoute: AppEditorPageAnnotationRoute,
  AppEditorProductionProgressRoute: AppEditorProductionProgressRoute,
  AppEditorRankingRiskRoute: AppEditorRankingRiskRoute,
  AppEditorSeriesReviewRoute: AppEditorSeriesReviewRoute,
  AppSeriesIdRoute: AppSeriesIdRouteWithChildren,
  AppSeriesNewRoute: AppSeriesNewRoute,
  AppSeriesIndexRoute: AppSeriesIndexRoute,
  AppPagesIdStudioRoute: AppPagesIdStudioRoute,
  AppChaptersIdPagesUploadRoute: AppChaptersIdPagesUploadRoute,
  AppEditorSeriesIdReviewRoute: AppEditorSeriesIdReviewRoute,
  AppEditorTasksIdFinalReviewRoute: AppEditorTasksIdFinalReviewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ReadSlugRouteChildren {
  ReadSlugChapterRoute: typeof ReadSlugChapterRoute
}

const ReadSlugRouteChildren: ReadSlugRouteChildren = {
  ReadSlugChapterRoute: ReadSlugChapterRoute,
}

const ReadSlugRouteWithChildren = ReadSlugRoute._addFileChildren(
  ReadSlugRouteChildren,
)

interface ReadRouteChildren {
  ReadSlugRoute: typeof ReadSlugRouteWithChildren
  ReadIndexRoute: typeof ReadIndexRoute
}

const ReadRouteChildren: ReadRouteChildren = {
  ReadSlugRoute: ReadSlugRouteWithChildren,
  ReadIndexRoute: ReadIndexRoute,
}

const ReadRouteWithChildren = ReadRoute._addFileChildren(ReadRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ReadRoute: ReadRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
