import { ActionItemList, ChapterCreationGateCard, ChapterProgressCard, ManuscriptUploadPanel, SeriesSummaryCard } from "@/shared/components/domain"
import { MFEmptyState } from "@/shared/components/feedback/MFEmptyState"
import { MFErrorState } from "@/shared/components/feedback/MFErrorState"
import { MFBadge, MFButton, MFCard, MFTable } from "@/shared/components/ui"
import { seriesDetailActions, chapterColumns, taskStatusUI, type ChapterRow } from "../utils/series-detail.mappers"
import type { Series } from "../api/series.types"

export function SeriesOverviewPanel({ series, canCreateChapter, selectedManuscripts, setSelectedManuscripts, chaptersCount }: { series: Series; canCreateChapter: boolean; selectedManuscripts: string[]; setSelectedManuscripts: (files: string[]) => void; chaptersCount: number }) {
  return <section className="grid gap-lg xl:grid-cols-[minmax(0,1fr)_24rem]"><div className="space-y-lg"><SeriesSummaryCard title={series.title} status={series.status} genre={series.genres.length > 0 ? series.genres.join(", ") : "Unclassified"} publicationType="Not supplied yet" description={series.synopsis} ownerLabel="Series owner" metadata={[`Slug: ${series.slug}`, `Updated: ${new Date(series.updatedAt).toLocaleDateString()}`]} /><ChapterCreationGateCard seriesTitle={series.title} canCreateChapter={canCreateChapter} reason="Chapter creation is allowed only after backend status is APPROVED, ONGOING, or AT_RISK." actionLabel={canCreateChapter ? "Backend gate ready" : "Create chapter blocked"} /><div><h2 className="mb-md text-title-lg text-on-surface">Chapter progress</h2><ChapterProgressCard title="Live chapters" status={chaptersCount > 0 ? "IN_PRODUCTION" : "DRAFT"} completed={chaptersCount} total={chaptersCount} progressLabel="Chapters loaded" description="Chapter records are loaded from the backend. Page-level progress remains a later page API slice." /></div></div><div className="space-y-lg"><ManuscriptUploadPanel title="Manuscript upload boundary" description="Local file selection preview. No storage request, signed URL, or manuscript submission is sent." constraints={["Original file storage is backend-owned and not connected here.", "Signed URL access remains out of scope for this story.", "Selected filenames below are browser-local only."]} accept=".pdf,.zip,.jpg,.jpeg,.png" multiple onFilesSelected={(files) => setSelectedManuscripts(Array.from(files, (file) => file.name))} />{selectedManuscripts.length > 0 ? <MFCard><h2 className="text-title-lg text-on-surface">Selected locally</h2><ul className="mt-lg list-disc space-y-xs pl-lg text-body-md text-on-surface-muted">{selectedManuscripts.map((fileName) => <li key={fileName} className="break-words">{fileName}</li>)}</ul></MFCard> : null}<div><h2 className="mb-md text-title-lg text-on-surface">Pending actions</h2><ActionItemList items={seriesDetailActions} statusMapping={taskStatusUI} /></div></div></section>
}

export function ChapterListPanel({ chapterError, chapterLoading, chapterRows, loadChapters }: { chapterError: string; chapterLoading: boolean; chapterRows: ChapterRow[]; loadChapters: () => Promise<void> }) {
  return <div><div className="mb-md flex flex-wrap items-center justify-between gap-md"><h2 className="text-title-lg text-on-surface">Chapter list</h2><MFBadge tone="success" size="md">API connected</MFBadge></div>{chapterError ? <MFErrorState title="Could not load chapters" description={chapterError} onRetry={() => void loadChapters()} /> : <MFTable caption="Series chapter list" rows={chapterRows} columns={chapterColumns} getRowKey={(chapter) => chapter.id} loading={chapterLoading} emptyTitle="No chapters for this Series" emptyDescription="Chapters appear here after backend chapter creation succeeds for an approved, ongoing, or at-risk Series." />}</div>
}

export function PagePreviewBoundaryPanel() {
  return <MFCard><h2 className="text-title-lg text-on-surface">Page preview boundary</h2><p className="mt-xs text-body-md text-on-surface-muted">This slice reads chapter metadata only. Protected page artwork still requires page APIs and signed file access.</p><div className="mt-lg rounded-3xl bg-surface-low p-lg"><MFEmptyState icon="image" title="Page previews not connected" description="Page thumbnails will appear only after the protected page workspace and signed URL flow are wired." /></div><div className="mt-md"><MFButton type="button" variant="outline" size="sm" disabled>Page API pending</MFButton></div></MFCard>
}
