import swaggerAutogen from "swagger-autogen"

const doc = {
  info: {
    version: "1.0.0",
    title: "MangaFlow API",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:3001",
  basePath: "/",
  schemes: ["http"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "Auth",
      description: "Authentication and User Management",
    },
    {
      name: "Admin",
      description: "Admin Operations",
    },
    {
      name: "Series",
      description: "Series Management",
    },
    {
      name: "Chapter",
      description: "Chapter and Page Management",
    },
    {
      name: "Task",
      description: "Assistant Task Assignment",
    },
    {
      name: "Submission",
      description: "Task Submission and Review",
    },
  ],
  securityDefinitions: {
    bearerAuth: {
      type: "http",
      scheme: "bearer",
      bearerFormat: "JWT",
    },
  },
}

const outputFile = "../swagger-output.json"
const endpointsFiles = ["./src/index.ts"]

swaggerAutogen({ openapi: "3.0.0" })(outputFile, endpointsFiles, doc)
