/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReadRouteImport } from './routes/read'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadIndexRouteImport } from './routes/read.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ReadSlugRouteImport } from './routes/read.$slug'
import { Route as AppSubmissionsRouteImport } from './routes/app.submissions'
import { Route as AppSeriesRouteImport } from './routes/app.series'
import { Route as AppRankingsRouteImport } from './routes/app.rankings'
import { Route as AppProposalsRouteImport } from './routes/app.proposals'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppEditorRouteImport } from './routes/app.editor'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppBoardRouteImport } from './routes/app.board'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as ReadSlugIndexRouteImport } from './routes/read.$slug.index'
import { Route as AppSubmissionsIndexRouteImport } from './routes/app.submissions.index'
import { Route as AppSeriesIndexRouteImport } from './routes/app.series.index'
import { Route as AppProposalsIndexRouteImport } from './routes/app.proposals.index'
import { Route as AppBoardIndexRouteImport } from './routes/app.board.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as ReadSlugChapterRouteImport } from './routes/read.$slug.$chapter'
import { Route as AppSubmissionsNewRouteImport } from './routes/app.submissions.new'
import { Route as AppSubmissionsIdRouteImport } from './routes/app.submissions.$id'
import { Route as AppProposalsNewRouteImport } from './routes/app.proposals.new'
import { Route as AppProposalsProposalIdRouteImport } from './routes/app.proposals.$proposalId'
import { Route as AppEditorSeriesRouteImport } from './routes/app.editor.series'
import { Route as AppEditorReviewRouteImport } from './routes/app.editor.review'
import { Route as AppEditorPublicationsRouteImport } from './routes/app.editor.publications'
import { Route as AppEditorNotificationsRouteImport } from './routes/app.editor.notifications'
import { Route as AppEditorDashboardRouteImport } from './routes/app.editor.dashboard'
import { Route as AppBoardSessionsRouteImport } from './routes/app.board.sessions'
import { Route as AppBoardRankingsRouteImport } from './routes/app.board.rankings'
import { Route as AppBoardQueueRouteImport } from './routes/app.board.queue'
import { Route as AppBoardNotificationsRouteImport } from './routes/app.board.notifications'
import { Route as AppBoardDecisionsRouteImport } from './routes/app.board.decisions'
import { Route as AppBoardDashboardRouteImport } from './routes/app.board.dashboard'
import { Route as AppBoardAtRiskRouteImport } from './routes/app.board.at-risk'
import { Route as AppBoardIdRouteImport } from './routes/app.board.$id'
import { Route as AppAssistantTasksRouteImport } from './routes/app.assistant.tasks'
import { Route as AppAssistantSubmissionsRouteImport } from './routes/app.assistant.submissions'
import { Route as AppAssistantNotificationsRouteImport } from './routes/app.assistant.notifications'
import { Route as AppAssistantEarningsRouteImport } from './routes/app.assistant.earnings'
import { Route as AppAssistantDashboardRouteImport } from './routes/app.assistant.dashboard'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminRatesRouteImport } from './routes/app.admin.rates'
import { Route as AppAdminNotificationsRouteImport } from './routes/app.admin.notifications'
import { Route as AppAdminDashboardRouteImport } from './routes/app.admin.dashboard'
import { Route as AppEditorSeriesIndexRouteImport } from './routes/app.editor.series.index'
import { Route as AppEditorReviewIndexRouteImport } from './routes/app.editor.review.index'
import { Route as AppBoardSessionsIndexRouteImport } from './routes/app.board.sessions.index'
import { Route as AppBoardRankingsIndexRouteImport } from './routes/app.board.rankings.index'
import { Route as AppSeriesSlugTabRouteImport } from './routes/app.series.$slug.$tab'
import { Route as AppMangakaSubmissionsReviewRouteImport } from './routes/app.mangaka.submissions.review'
import { Route as AppEditorReviewSubmissionIdRouteImport } from './routes/app.editor.review.$submissionId'
import { Route as AppEditorProposalsProposalIdRouteImport } from './routes/app.editor.proposals.$proposalId'
import { Route as AppBoardSessionsNewRouteImport } from './routes/app.board.sessions.new'
import { Route as AppBoardSessionsSidRouteImport } from './routes/app.board.sessions.$sid'
import { Route as AppBoardRankingsImportRouteImport } from './routes/app.board.rankings.import'
import { Route as AppBoardProposalsProposalIdRouteImport } from './routes/app.board.proposals.$proposalId'
import { Route as AppMangakaSubmissionsSubmissionIdReviewRouteImport } from './routes/app.mangaka.submissions.$submissionId.review'
import { Route as AppEditorStoryboardsStoryboardIdReviewRouteImport } from './routes/app.editor.storyboards.$storyboardId.review'
import { Route as AppEditorSeriesSeriesIdStudioRouteImport } from './routes/app.editor.series.$seriesId.studio'
import { Route as AppEditorChaptersChapterIdReviewRouteImport } from './routes/app.editor.chapters.$chapterId.review'
import { Route as AppEditorChaptersChapterIdAnnotateRouteImport } from './routes/app.editor.chapters.$chapterId.annotate'
import { Route as AppAssistantTasksTaskIdStudioRouteImport } from './routes/app.assistant.tasks.$taskId.studio'
import { Route as AppAssistantSeriesSeriesIdStudioRouteImport } from './routes/app.assistant.series.$seriesId.studio'

const ReadRoute = ReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadIndexRoute = ReadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReadRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ReadSlugRoute = ReadSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ReadRoute,
} as any)
const AppSubmissionsRoute = AppSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppRoute,
} as any)
const AppSeriesRoute = AppSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingsRoute = AppRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AppRoute,
} as any)
const AppProposalsRoute = AppProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppEditorRoute = AppEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardRoute = AppBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ReadSlugIndexRoute = ReadSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReadSlugRoute,
} as any)
const AppSubmissionsIndexRoute = AppSubmissionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSubmissionsRoute,
} as any)
const AppSeriesIndexRoute = AppSeriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSeriesRoute,
} as any)
const AppProposalsIndexRoute = AppProposalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProposalsRoute,
} as any)
const AppBoardIndexRoute = AppBoardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBoardRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const ReadSlugChapterRoute = ReadSlugChapterRouteImport.update({
  id: '/$chapter',
  path: '/$chapter',
  getParentRoute: () => ReadSlugRoute,
} as any)
const AppSubmissionsNewRoute = AppSubmissionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSubmissionsRoute,
} as any)
const AppSubmissionsIdRoute = AppSubmissionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSubmissionsRoute,
} as any)
const AppProposalsNewRoute = AppProposalsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppProposalsRoute,
} as any)
const AppProposalsProposalIdRoute = AppProposalsProposalIdRouteImport.update({
  id: '/$proposalId',
  path: '/$proposalId',
  getParentRoute: () => AppProposalsRoute,
} as any)
const AppEditorSeriesRoute = AppEditorSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => AppEditorRoute,
} as any)
const AppEditorReviewRoute = AppEditorReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppEditorRoute,
} as any)
const AppEditorPublicationsRoute = AppEditorPublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => AppEditorRoute,
} as any)
const AppEditorNotificationsRoute = AppEditorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppEditorRoute,
} as any)
const AppEditorDashboardRoute = AppEditorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppEditorRoute,
} as any)
const AppBoardSessionsRoute = AppBoardSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppBoardRoute,
} as any)
const AppBoardRankingsRoute = AppBoardRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AppBoardRoute,
} as any)
const AppBoardQueueRoute = AppBoardQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppBoardRoute,
} as any)
const AppBoardNotificationsRoute = AppBoardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppBoardRoute,
} as any)
const AppBoardDecisionsRoute = AppBoardDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AppBoardRoute,
} as any)
const AppBoardDashboardRoute = AppBoardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppBoardRoute,
} as any)
const AppBoardAtRiskRoute = AppBoardAtRiskRouteImport.update({
  id: '/at-risk',
  path: '/at-risk',
  getParentRoute: () => AppBoardRoute,
} as any)
const AppBoardIdRoute = AppBoardIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppBoardRoute,
} as any)
const AppAssistantTasksRoute = AppAssistantTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppAssistantRoute,
} as any)
const AppAssistantSubmissionsRoute = AppAssistantSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppAssistantRoute,
} as any)
const AppAssistantNotificationsRoute =
  AppAssistantNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppAssistantRoute,
  } as any)
const AppAssistantEarningsRoute = AppAssistantEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AppAssistantRoute,
} as any)
const AppAssistantDashboardRoute = AppAssistantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppAssistantRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRatesRoute = AppAdminRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminNotificationsRoute = AppAdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppEditorSeriesIndexRoute = AppEditorSeriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEditorSeriesRoute,
} as any)
const AppEditorReviewIndexRoute = AppEditorReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEditorReviewRoute,
} as any)
const AppBoardSessionsIndexRoute = AppBoardSessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBoardSessionsRoute,
} as any)
const AppBoardRankingsIndexRoute = AppBoardRankingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBoardRankingsRoute,
} as any)
const AppSeriesSlugTabRoute = AppSeriesSlugTabRouteImport.update({
  id: '/$slug/$tab',
  path: '/$slug/$tab',
  getParentRoute: () => AppSeriesRoute,
} as any)
const AppMangakaSubmissionsReviewRoute =
  AppMangakaSubmissionsReviewRouteImport.update({
    id: '/mangaka/submissions/review',
    path: '/mangaka/submissions/review',
    getParentRoute: () => AppRoute,
  } as any)
const AppEditorReviewSubmissionIdRoute =
  AppEditorReviewSubmissionIdRouteImport.update({
    id: '/$submissionId',
    path: '/$submissionId',
    getParentRoute: () => AppEditorReviewRoute,
  } as any)
const AppEditorProposalsProposalIdRoute =
  AppEditorProposalsProposalIdRouteImport.update({
    id: '/proposals/$proposalId',
    path: '/proposals/$proposalId',
    getParentRoute: () => AppEditorRoute,
  } as any)
const AppBoardSessionsNewRoute = AppBoardSessionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppBoardSessionsRoute,
} as any)
const AppBoardSessionsSidRoute = AppBoardSessionsSidRouteImport.update({
  id: '/$sid',
  path: '/$sid',
  getParentRoute: () => AppBoardSessionsRoute,
} as any)
const AppBoardRankingsImportRoute = AppBoardRankingsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppBoardRankingsRoute,
} as any)
const AppBoardProposalsProposalIdRoute =
  AppBoardProposalsProposalIdRouteImport.update({
    id: '/proposals/$proposalId',
    path: '/proposals/$proposalId',
    getParentRoute: () => AppBoardRoute,
  } as any)
const AppMangakaSubmissionsSubmissionIdReviewRoute =
  AppMangakaSubmissionsSubmissionIdReviewRouteImport.update({
    id: '/mangaka/submissions/$submissionId/review',
    path: '/mangaka/submissions/$submissionId/review',
    getParentRoute: () => AppRoute,
  } as any)
const AppEditorStoryboardsStoryboardIdReviewRoute =
  AppEditorStoryboardsStoryboardIdReviewRouteImport.update({
    id: '/storyboards/$storyboardId/review',
    path: '/storyboards/$storyboardId/review',
    getParentRoute: () => AppEditorRoute,
  } as any)
const AppEditorSeriesSeriesIdStudioRoute =
  AppEditorSeriesSeriesIdStudioRouteImport.update({
    id: '/$seriesId/studio',
    path: '/$seriesId/studio',
    getParentRoute: () => AppEditorSeriesRoute,
  } as any)
const AppEditorChaptersChapterIdReviewRoute =
  AppEditorChaptersChapterIdReviewRouteImport.update({
    id: '/chapters/$chapterId/review',
    path: '/chapters/$chapterId/review',
    getParentRoute: () => AppEditorRoute,
  } as any)
const AppEditorChaptersChapterIdAnnotateRoute =
  AppEditorChaptersChapterIdAnnotateRouteImport.update({
    id: '/chapters/$chapterId/annotate',
    path: '/chapters/$chapterId/annotate',
    getParentRoute: () => AppEditorRoute,
  } as any)
const AppAssistantTasksTaskIdStudioRoute =
  AppAssistantTasksTaskIdStudioRouteImport.update({
    id: '/$taskId/studio',
    path: '/$taskId/studio',
    getParentRoute: () => AppAssistantTasksRoute,
  } as any)
const AppAssistantSeriesSeriesIdStudioRoute =
  AppAssistantSeriesSeriesIdStudioRouteImport.update({
    id: '/series/$seriesId/studio',
    path: '/series/$seriesId/studio',
    getParentRoute: () => AppAssistantRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/read': typeof ReadRouteWithChildren
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/assistant': typeof AppAssistantRouteWithChildren
  '/app/board': typeof AppBoardRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/editor': typeof AppEditorRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/proposals': typeof AppProposalsRouteWithChildren
  '/app/rankings': typeof AppRankingsRoute
  '/app/series': typeof AppSeriesRouteWithChildren
  '/app/submissions': typeof AppSubmissionsRouteWithChildren
  '/read/$slug': typeof ReadSlugRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/read/': typeof ReadIndexRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/admin/notifications': typeof AppAdminNotificationsRoute
  '/app/admin/rates': typeof AppAdminRatesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/assistant/dashboard': typeof AppAssistantDashboardRoute
  '/app/assistant/earnings': typeof AppAssistantEarningsRoute
  '/app/assistant/notifications': typeof AppAssistantNotificationsRoute
  '/app/assistant/submissions': typeof AppAssistantSubmissionsRoute
  '/app/assistant/tasks': typeof AppAssistantTasksRouteWithChildren
  '/app/board/$id': typeof AppBoardIdRoute
  '/app/board/at-risk': typeof AppBoardAtRiskRoute
  '/app/board/dashboard': typeof AppBoardDashboardRoute
  '/app/board/decisions': typeof AppBoardDecisionsRoute
  '/app/board/notifications': typeof AppBoardNotificationsRoute
  '/app/board/queue': typeof AppBoardQueueRoute
  '/app/board/rankings': typeof AppBoardRankingsRouteWithChildren
  '/app/board/sessions': typeof AppBoardSessionsRouteWithChildren
  '/app/editor/dashboard': typeof AppEditorDashboardRoute
  '/app/editor/notifications': typeof AppEditorNotificationsRoute
  '/app/editor/publications': typeof AppEditorPublicationsRoute
  '/app/editor/review': typeof AppEditorReviewRouteWithChildren
  '/app/editor/series': typeof AppEditorSeriesRouteWithChildren
  '/app/proposals/$proposalId': typeof AppProposalsProposalIdRoute
  '/app/proposals/new': typeof AppProposalsNewRoute
  '/app/submissions/$id': typeof AppSubmissionsIdRoute
  '/app/submissions/new': typeof AppSubmissionsNewRoute
  '/read/$slug/$chapter': typeof ReadSlugChapterRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/board/': typeof AppBoardIndexRoute
  '/app/proposals/': typeof AppProposalsIndexRoute
  '/app/series/': typeof AppSeriesIndexRoute
  '/app/submissions/': typeof AppSubmissionsIndexRoute
  '/read/$slug/': typeof ReadSlugIndexRoute
  '/app/board/proposals/$proposalId': typeof AppBoardProposalsProposalIdRoute
  '/app/board/rankings/import': typeof AppBoardRankingsImportRoute
  '/app/board/sessions/$sid': typeof AppBoardSessionsSidRoute
  '/app/board/sessions/new': typeof AppBoardSessionsNewRoute
  '/app/editor/proposals/$proposalId': typeof AppEditorProposalsProposalIdRoute
  '/app/editor/review/$submissionId': typeof AppEditorReviewSubmissionIdRoute
  '/app/mangaka/submissions/review': typeof AppMangakaSubmissionsReviewRoute
  '/app/series/$slug/$tab': typeof AppSeriesSlugTabRoute
  '/app/board/rankings/': typeof AppBoardRankingsIndexRoute
  '/app/board/sessions/': typeof AppBoardSessionsIndexRoute
  '/app/editor/review/': typeof AppEditorReviewIndexRoute
  '/app/editor/series/': typeof AppEditorSeriesIndexRoute
  '/app/assistant/series/$seriesId/studio': typeof AppAssistantSeriesSeriesIdStudioRoute
  '/app/assistant/tasks/$taskId/studio': typeof AppAssistantTasksTaskIdStudioRoute
  '/app/editor/chapters/$chapterId/annotate': typeof AppEditorChaptersChapterIdAnnotateRoute
  '/app/editor/chapters/$chapterId/review': typeof AppEditorChaptersChapterIdReviewRoute
  '/app/editor/series/$seriesId/studio': typeof AppEditorSeriesSeriesIdStudioRoute
  '/app/editor/storyboards/$storyboardId/review': typeof AppEditorStoryboardsStoryboardIdReviewRoute
  '/app/mangaka/submissions/$submissionId/review': typeof AppMangakaSubmissionsSubmissionIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/assistant': typeof AppAssistantRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/editor': typeof AppEditorRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/rankings': typeof AppRankingsRoute
  '/app': typeof AppIndexRoute
  '/read': typeof ReadIndexRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/admin/notifications': typeof AppAdminNotificationsRoute
  '/app/admin/rates': typeof AppAdminRatesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/assistant/dashboard': typeof AppAssistantDashboardRoute
  '/app/assistant/earnings': typeof AppAssistantEarningsRoute
  '/app/assistant/notifications': typeof AppAssistantNotificationsRoute
  '/app/assistant/submissions': typeof AppAssistantSubmissionsRoute
  '/app/assistant/tasks': typeof AppAssistantTasksRouteWithChildren
  '/app/board/$id': typeof AppBoardIdRoute
  '/app/board/at-risk': typeof AppBoardAtRiskRoute
  '/app/board/dashboard': typeof AppBoardDashboardRoute
  '/app/board/decisions': typeof AppBoardDecisionsRoute
  '/app/board/notifications': typeof AppBoardNotificationsRoute
  '/app/board/queue': typeof AppBoardQueueRoute
  '/app/editor/dashboard': typeof AppEditorDashboardRoute
  '/app/editor/notifications': typeof AppEditorNotificationsRoute
  '/app/editor/publications': typeof AppEditorPublicationsRoute
  '/app/proposals/$proposalId': typeof AppProposalsProposalIdRoute
  '/app/proposals/new': typeof AppProposalsNewRoute
  '/app/submissions/$id': typeof AppSubmissionsIdRoute
  '/app/submissions/new': typeof AppSubmissionsNewRoute
  '/read/$slug/$chapter': typeof ReadSlugChapterRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/board': typeof AppBoardIndexRoute
  '/app/proposals': typeof AppProposalsIndexRoute
  '/app/series': typeof AppSeriesIndexRoute
  '/app/submissions': typeof AppSubmissionsIndexRoute
  '/read/$slug': typeof ReadSlugIndexRoute
  '/app/board/proposals/$proposalId': typeof AppBoardProposalsProposalIdRoute
  '/app/board/rankings/import': typeof AppBoardRankingsImportRoute
  '/app/board/sessions/$sid': typeof AppBoardSessionsSidRoute
  '/app/board/sessions/new': typeof AppBoardSessionsNewRoute
  '/app/editor/proposals/$proposalId': typeof AppEditorProposalsProposalIdRoute
  '/app/editor/review/$submissionId': typeof AppEditorReviewSubmissionIdRoute
  '/app/mangaka/submissions/review': typeof AppMangakaSubmissionsReviewRoute
  '/app/series/$slug/$tab': typeof AppSeriesSlugTabRoute
  '/app/board/rankings': typeof AppBoardRankingsIndexRoute
  '/app/board/sessions': typeof AppBoardSessionsIndexRoute
  '/app/editor/review': typeof AppEditorReviewIndexRoute
  '/app/editor/series': typeof AppEditorSeriesIndexRoute
  '/app/assistant/series/$seriesId/studio': typeof AppAssistantSeriesSeriesIdStudioRoute
  '/app/assistant/tasks/$taskId/studio': typeof AppAssistantTasksTaskIdStudioRoute
  '/app/editor/chapters/$chapterId/annotate': typeof AppEditorChaptersChapterIdAnnotateRoute
  '/app/editor/chapters/$chapterId/review': typeof AppEditorChaptersChapterIdReviewRoute
  '/app/editor/series/$seriesId/studio': typeof AppEditorSeriesSeriesIdStudioRoute
  '/app/editor/storyboards/$storyboardId/review': typeof AppEditorStoryboardsStoryboardIdReviewRoute
  '/app/mangaka/submissions/$submissionId/review': typeof AppMangakaSubmissionsSubmissionIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/read': typeof ReadRouteWithChildren
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/assistant': typeof AppAssistantRouteWithChildren
  '/app/board': typeof AppBoardRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/editor': typeof AppEditorRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/proposals': typeof AppProposalsRouteWithChildren
  '/app/rankings': typeof AppRankingsRoute
  '/app/series': typeof AppSeriesRouteWithChildren
  '/app/submissions': typeof AppSubmissionsRouteWithChildren
  '/read/$slug': typeof ReadSlugRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/read/': typeof ReadIndexRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/admin/notifications': typeof AppAdminNotificationsRoute
  '/app/admin/rates': typeof AppAdminRatesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/assistant/dashboard': typeof AppAssistantDashboardRoute
  '/app/assistant/earnings': typeof AppAssistantEarningsRoute
  '/app/assistant/notifications': typeof AppAssistantNotificationsRoute
  '/app/assistant/submissions': typeof AppAssistantSubmissionsRoute
  '/app/assistant/tasks': typeof AppAssistantTasksRouteWithChildren
  '/app/board/$id': typeof AppBoardIdRoute
  '/app/board/at-risk': typeof AppBoardAtRiskRoute
  '/app/board/dashboard': typeof AppBoardDashboardRoute
  '/app/board/decisions': typeof AppBoardDecisionsRoute
  '/app/board/notifications': typeof AppBoardNotificationsRoute
  '/app/board/queue': typeof AppBoardQueueRoute
  '/app/board/rankings': typeof AppBoardRankingsRouteWithChildren
  '/app/board/sessions': typeof AppBoardSessionsRouteWithChildren
  '/app/editor/dashboard': typeof AppEditorDashboardRoute
  '/app/editor/notifications': typeof AppEditorNotificationsRoute
  '/app/editor/publications': typeof AppEditorPublicationsRoute
  '/app/editor/review': typeof AppEditorReviewRouteWithChildren
  '/app/editor/series': typeof AppEditorSeriesRouteWithChildren
  '/app/proposals/$proposalId': typeof AppProposalsProposalIdRoute
  '/app/proposals/new': typeof AppProposalsNewRoute
  '/app/submissions/$id': typeof AppSubmissionsIdRoute
  '/app/submissions/new': typeof AppSubmissionsNewRoute
  '/read/$slug/$chapter': typeof ReadSlugChapterRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/board/': typeof AppBoardIndexRoute
  '/app/proposals/': typeof AppProposalsIndexRoute
  '/app/series/': typeof AppSeriesIndexRoute
  '/app/submissions/': typeof AppSubmissionsIndexRoute
  '/read/$slug/': typeof ReadSlugIndexRoute
  '/app/board/proposals/$proposalId': typeof AppBoardProposalsProposalIdRoute
  '/app/board/rankings/import': typeof AppBoardRankingsImportRoute
  '/app/board/sessions/$sid': typeof AppBoardSessionsSidRoute
  '/app/board/sessions/new': typeof AppBoardSessionsNewRoute
  '/app/editor/proposals/$proposalId': typeof AppEditorProposalsProposalIdRoute
  '/app/editor/review/$submissionId': typeof AppEditorReviewSubmissionIdRoute
  '/app/mangaka/submissions/review': typeof AppMangakaSubmissionsReviewRoute
  '/app/series/$slug/$tab': typeof AppSeriesSlugTabRoute
  '/app/board/rankings/': typeof AppBoardRankingsIndexRoute
  '/app/board/sessions/': typeof AppBoardSessionsIndexRoute
  '/app/editor/review/': typeof AppEditorReviewIndexRoute
  '/app/editor/series/': typeof AppEditorSeriesIndexRoute
  '/app/assistant/series/$seriesId/studio': typeof AppAssistantSeriesSeriesIdStudioRoute
  '/app/assistant/tasks/$taskId/studio': typeof AppAssistantTasksTaskIdStudioRoute
  '/app/editor/chapters/$chapterId/annotate': typeof AppEditorChaptersChapterIdAnnotateRoute
  '/app/editor/chapters/$chapterId/review': typeof AppEditorChaptersChapterIdReviewRoute
  '/app/editor/series/$seriesId/studio': typeof AppEditorSeriesSeriesIdStudioRoute
  '/app/editor/storyboards/$storyboardId/review': typeof AppEditorStoryboardsStoryboardIdReviewRoute
  '/app/mangaka/submissions/$submissionId/review': typeof AppMangakaSubmissionsSubmissionIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/read'
    | '/app/admin'
    | '/app/assistant'
    | '/app/board'
    | '/app/dashboard'
    | '/app/editor'
    | '/app/notifications'
    | '/app/proposals'
    | '/app/rankings'
    | '/app/series'
    | '/app/submissions'
    | '/read/$slug'
    | '/app/'
    | '/read/'
    | '/app/admin/dashboard'
    | '/app/admin/notifications'
    | '/app/admin/rates'
    | '/app/admin/users'
    | '/app/assistant/dashboard'
    | '/app/assistant/earnings'
    | '/app/assistant/notifications'
    | '/app/assistant/submissions'
    | '/app/assistant/tasks'
    | '/app/board/$id'
    | '/app/board/at-risk'
    | '/app/board/dashboard'
    | '/app/board/decisions'
    | '/app/board/notifications'
    | '/app/board/queue'
    | '/app/board/rankings'
    | '/app/board/sessions'
    | '/app/editor/dashboard'
    | '/app/editor/notifications'
    | '/app/editor/publications'
    | '/app/editor/review'
    | '/app/editor/series'
    | '/app/proposals/$proposalId'
    | '/app/proposals/new'
    | '/app/submissions/$id'
    | '/app/submissions/new'
    | '/read/$slug/$chapter'
    | '/app/admin/'
    | '/app/board/'
    | '/app/proposals/'
    | '/app/series/'
    | '/app/submissions/'
    | '/read/$slug/'
    | '/app/board/proposals/$proposalId'
    | '/app/board/rankings/import'
    | '/app/board/sessions/$sid'
    | '/app/board/sessions/new'
    | '/app/editor/proposals/$proposalId'
    | '/app/editor/review/$submissionId'
    | '/app/mangaka/submissions/review'
    | '/app/series/$slug/$tab'
    | '/app/board/rankings/'
    | '/app/board/sessions/'
    | '/app/editor/review/'
    | '/app/editor/series/'
    | '/app/assistant/series/$seriesId/studio'
    | '/app/assistant/tasks/$taskId/studio'
    | '/app/editor/chapters/$chapterId/annotate'
    | '/app/editor/chapters/$chapterId/review'
    | '/app/editor/series/$seriesId/studio'
    | '/app/editor/storyboards/$storyboardId/review'
    | '/app/mangaka/submissions/$submissionId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/assistant'
    | '/app/dashboard'
    | '/app/editor'
    | '/app/notifications'
    | '/app/rankings'
    | '/app'
    | '/read'
    | '/app/admin/dashboard'
    | '/app/admin/notifications'
    | '/app/admin/rates'
    | '/app/admin/users'
    | '/app/assistant/dashboard'
    | '/app/assistant/earnings'
    | '/app/assistant/notifications'
    | '/app/assistant/submissions'
    | '/app/assistant/tasks'
    | '/app/board/$id'
    | '/app/board/at-risk'
    | '/app/board/dashboard'
    | '/app/board/decisions'
    | '/app/board/notifications'
    | '/app/board/queue'
    | '/app/editor/dashboard'
    | '/app/editor/notifications'
    | '/app/editor/publications'
    | '/app/proposals/$proposalId'
    | '/app/proposals/new'
    | '/app/submissions/$id'
    | '/app/submissions/new'
    | '/read/$slug/$chapter'
    | '/app/admin'
    | '/app/board'
    | '/app/proposals'
    | '/app/series'
    | '/app/submissions'
    | '/read/$slug'
    | '/app/board/proposals/$proposalId'
    | '/app/board/rankings/import'
    | '/app/board/sessions/$sid'
    | '/app/board/sessions/new'
    | '/app/editor/proposals/$proposalId'
    | '/app/editor/review/$submissionId'
    | '/app/mangaka/submissions/review'
    | '/app/series/$slug/$tab'
    | '/app/board/rankings'
    | '/app/board/sessions'
    | '/app/editor/review'
    | '/app/editor/series'
    | '/app/assistant/series/$seriesId/studio'
    | '/app/assistant/tasks/$taskId/studio'
    | '/app/editor/chapters/$chapterId/annotate'
    | '/app/editor/chapters/$chapterId/review'
    | '/app/editor/series/$seriesId/studio'
    | '/app/editor/storyboards/$storyboardId/review'
    | '/app/mangaka/submissions/$submissionId/review'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/read'
    | '/app/admin'
    | '/app/assistant'
    | '/app/board'
    | '/app/dashboard'
    | '/app/editor'
    | '/app/notifications'
    | '/app/proposals'
    | '/app/rankings'
    | '/app/series'
    | '/app/submissions'
    | '/read/$slug'
    | '/app/'
    | '/read/'
    | '/app/admin/dashboard'
    | '/app/admin/notifications'
    | '/app/admin/rates'
    | '/app/admin/users'
    | '/app/assistant/dashboard'
    | '/app/assistant/earnings'
    | '/app/assistant/notifications'
    | '/app/assistant/submissions'
    | '/app/assistant/tasks'
    | '/app/board/$id'
    | '/app/board/at-risk'
    | '/app/board/dashboard'
    | '/app/board/decisions'
    | '/app/board/notifications'
    | '/app/board/queue'
    | '/app/board/rankings'
    | '/app/board/sessions'
    | '/app/editor/dashboard'
    | '/app/editor/notifications'
    | '/app/editor/publications'
    | '/app/editor/review'
    | '/app/editor/series'
    | '/app/proposals/$proposalId'
    | '/app/proposals/new'
    | '/app/submissions/$id'
    | '/app/submissions/new'
    | '/read/$slug/$chapter'
    | '/app/admin/'
    | '/app/board/'
    | '/app/proposals/'
    | '/app/series/'
    | '/app/submissions/'
    | '/read/$slug/'
    | '/app/board/proposals/$proposalId'
    | '/app/board/rankings/import'
    | '/app/board/sessions/$sid'
    | '/app/board/sessions/new'
    | '/app/editor/proposals/$proposalId'
    | '/app/editor/review/$submissionId'
    | '/app/mangaka/submissions/review'
    | '/app/series/$slug/$tab'
    | '/app/board/rankings/'
    | '/app/board/sessions/'
    | '/app/editor/review/'
    | '/app/editor/series/'
    | '/app/assistant/series/$seriesId/studio'
    | '/app/assistant/tasks/$taskId/studio'
    | '/app/editor/chapters/$chapterId/annotate'
    | '/app/editor/chapters/$chapterId/review'
    | '/app/editor/series/$seriesId/studio'
    | '/app/editor/storyboards/$storyboardId/review'
    | '/app/mangaka/submissions/$submissionId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ReadRoute: typeof ReadRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/read': {
      id: '/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof ReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/': {
      id: '/read/'
      path: '/'
      fullPath: '/read/'
      preLoaderRoute: typeof ReadIndexRouteImport
      parentRoute: typeof ReadRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/read/$slug': {
      id: '/read/$slug'
      path: '/$slug'
      fullPath: '/read/$slug'
      preLoaderRoute: typeof ReadSlugRouteImport
      parentRoute: typeof ReadRoute
    }
    '/app/submissions': {
      id: '/app/submissions'
      path: '/submissions'
      fullPath: '/app/submissions'
      preLoaderRoute: typeof AppSubmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/series': {
      id: '/app/series'
      path: '/series'
      fullPath: '/app/series'
      preLoaderRoute: typeof AppSeriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rankings': {
      id: '/app/rankings'
      path: '/rankings'
      fullPath: '/app/rankings'
      preLoaderRoute: typeof AppRankingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/proposals': {
      id: '/app/proposals'
      path: '/proposals'
      fullPath: '/app/proposals'
      preLoaderRoute: typeof AppProposalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editor': {
      id: '/app/editor'
      path: '/editor'
      fullPath: '/app/editor'
      preLoaderRoute: typeof AppEditorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/board': {
      id: '/app/board'
      path: '/board'
      fullPath: '/app/board'
      preLoaderRoute: typeof AppBoardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/read/$slug/': {
      id: '/read/$slug/'
      path: '/'
      fullPath: '/read/$slug/'
      preLoaderRoute: typeof ReadSlugIndexRouteImport
      parentRoute: typeof ReadSlugRoute
    }
    '/app/submissions/': {
      id: '/app/submissions/'
      path: '/'
      fullPath: '/app/submissions/'
      preLoaderRoute: typeof AppSubmissionsIndexRouteImport
      parentRoute: typeof AppSubmissionsRoute
    }
    '/app/series/': {
      id: '/app/series/'
      path: '/'
      fullPath: '/app/series/'
      preLoaderRoute: typeof AppSeriesIndexRouteImport
      parentRoute: typeof AppSeriesRoute
    }
    '/app/proposals/': {
      id: '/app/proposals/'
      path: '/'
      fullPath: '/app/proposals/'
      preLoaderRoute: typeof AppProposalsIndexRouteImport
      parentRoute: typeof AppProposalsRoute
    }
    '/app/board/': {
      id: '/app/board/'
      path: '/'
      fullPath: '/app/board/'
      preLoaderRoute: typeof AppBoardIndexRouteImport
      parentRoute: typeof AppBoardRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/read/$slug/$chapter': {
      id: '/read/$slug/$chapter'
      path: '/$chapter'
      fullPath: '/read/$slug/$chapter'
      preLoaderRoute: typeof ReadSlugChapterRouteImport
      parentRoute: typeof ReadSlugRoute
    }
    '/app/submissions/new': {
      id: '/app/submissions/new'
      path: '/new'
      fullPath: '/app/submissions/new'
      preLoaderRoute: typeof AppSubmissionsNewRouteImport
      parentRoute: typeof AppSubmissionsRoute
    }
    '/app/submissions/$id': {
      id: '/app/submissions/$id'
      path: '/$id'
      fullPath: '/app/submissions/$id'
      preLoaderRoute: typeof AppSubmissionsIdRouteImport
      parentRoute: typeof AppSubmissionsRoute
    }
    '/app/proposals/new': {
      id: '/app/proposals/new'
      path: '/new'
      fullPath: '/app/proposals/new'
      preLoaderRoute: typeof AppProposalsNewRouteImport
      parentRoute: typeof AppProposalsRoute
    }
    '/app/proposals/$proposalId': {
      id: '/app/proposals/$proposalId'
      path: '/$proposalId'
      fullPath: '/app/proposals/$proposalId'
      preLoaderRoute: typeof AppProposalsProposalIdRouteImport
      parentRoute: typeof AppProposalsRoute
    }
    '/app/editor/series': {
      id: '/app/editor/series'
      path: '/series'
      fullPath: '/app/editor/series'
      preLoaderRoute: typeof AppEditorSeriesRouteImport
      parentRoute: typeof AppEditorRoute
    }
    '/app/editor/review': {
      id: '/app/editor/review'
      path: '/review'
      fullPath: '/app/editor/review'
      preLoaderRoute: typeof AppEditorReviewRouteImport
      parentRoute: typeof AppEditorRoute
    }
    '/app/editor/publications': {
      id: '/app/editor/publications'
      path: '/publications'
      fullPath: '/app/editor/publications'
      preLoaderRoute: typeof AppEditorPublicationsRouteImport
      parentRoute: typeof AppEditorRoute
    }
    '/app/editor/notifications': {
      id: '/app/editor/notifications'
      path: '/notifications'
      fullPath: '/app/editor/notifications'
      preLoaderRoute: typeof AppEditorNotificationsRouteImport
      parentRoute: typeof AppEditorRoute
    }
    '/app/editor/dashboard': {
      id: '/app/editor/dashboard'
      path: '/dashboard'
      fullPath: '/app/editor/dashboard'
      preLoaderRoute: typeof AppEditorDashboardRouteImport
      parentRoute: typeof AppEditorRoute
    }
    '/app/board/sessions': {
      id: '/app/board/sessions'
      path: '/sessions'
      fullPath: '/app/board/sessions'
      preLoaderRoute: typeof AppBoardSessionsRouteImport
      parentRoute: typeof AppBoardRoute
    }
    '/app/board/rankings': {
      id: '/app/board/rankings'
      path: '/rankings'
      fullPath: '/app/board/rankings'
      preLoaderRoute: typeof AppBoardRankingsRouteImport
      parentRoute: typeof AppBoardRoute
    }
    '/app/board/queue': {
      id: '/app/board/queue'
      path: '/queue'
      fullPath: '/app/board/queue'
      preLoaderRoute: typeof AppBoardQueueRouteImport
      parentRoute: typeof AppBoardRoute
    }
    '/app/board/notifications': {
      id: '/app/board/notifications'
      path: '/notifications'
      fullPath: '/app/board/notifications'
      preLoaderRoute: typeof AppBoardNotificationsRouteImport
      parentRoute: typeof AppBoardRoute
    }
    '/app/board/decisions': {
      id: '/app/board/decisions'
      path: '/decisions'
      fullPath: '/app/board/decisions'
      preLoaderRoute: typeof AppBoardDecisionsRouteImport
      parentRoute: typeof AppBoardRoute
    }
    '/app/board/dashboard': {
      id: '/app/board/dashboard'
      path: '/dashboard'
      fullPath: '/app/board/dashboard'
      preLoaderRoute: typeof AppBoardDashboardRouteImport
      parentRoute: typeof AppBoardRoute
    }
    '/app/board/at-risk': {
      id: '/app/board/at-risk'
      path: '/at-risk'
      fullPath: '/app/board/at-risk'
      preLoaderRoute: typeof AppBoardAtRiskRouteImport
      parentRoute: typeof AppBoardRoute
    }
    '/app/board/$id': {
      id: '/app/board/$id'
      path: '/$id'
      fullPath: '/app/board/$id'
      preLoaderRoute: typeof AppBoardIdRouteImport
      parentRoute: typeof AppBoardRoute
    }
    '/app/assistant/tasks': {
      id: '/app/assistant/tasks'
      path: '/tasks'
      fullPath: '/app/assistant/tasks'
      preLoaderRoute: typeof AppAssistantTasksRouteImport
      parentRoute: typeof AppAssistantRoute
    }
    '/app/assistant/submissions': {
      id: '/app/assistant/submissions'
      path: '/submissions'
      fullPath: '/app/assistant/submissions'
      preLoaderRoute: typeof AppAssistantSubmissionsRouteImport
      parentRoute: typeof AppAssistantRoute
    }
    '/app/assistant/notifications': {
      id: '/app/assistant/notifications'
      path: '/notifications'
      fullPath: '/app/assistant/notifications'
      preLoaderRoute: typeof AppAssistantNotificationsRouteImport
      parentRoute: typeof AppAssistantRoute
    }
    '/app/assistant/earnings': {
      id: '/app/assistant/earnings'
      path: '/earnings'
      fullPath: '/app/assistant/earnings'
      preLoaderRoute: typeof AppAssistantEarningsRouteImport
      parentRoute: typeof AppAssistantRoute
    }
    '/app/assistant/dashboard': {
      id: '/app/assistant/dashboard'
      path: '/dashboard'
      fullPath: '/app/assistant/dashboard'
      preLoaderRoute: typeof AppAssistantDashboardRouteImport
      parentRoute: typeof AppAssistantRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/rates': {
      id: '/app/admin/rates'
      path: '/rates'
      fullPath: '/app/admin/rates'
      preLoaderRoute: typeof AppAdminRatesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/notifications': {
      id: '/app/admin/notifications'
      path: '/notifications'
      fullPath: '/app/admin/notifications'
      preLoaderRoute: typeof AppAdminNotificationsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/dashboard': {
      id: '/app/admin/dashboard'
      path: '/dashboard'
      fullPath: '/app/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/editor/series/': {
      id: '/app/editor/series/'
      path: '/'
      fullPath: '/app/editor/series/'
      preLoaderRoute: typeof AppEditorSeriesIndexRouteImport
      parentRoute: typeof AppEditorSeriesRoute
    }
    '/app/editor/review/': {
      id: '/app/editor/review/'
      path: '/'
      fullPath: '/app/editor/review/'
      preLoaderRoute: typeof AppEditorReviewIndexRouteImport
      parentRoute: typeof AppEditorReviewRoute
    }
    '/app/board/sessions/': {
      id: '/app/board/sessions/'
      path: '/'
      fullPath: '/app/board/sessions/'
      preLoaderRoute: typeof AppBoardSessionsIndexRouteImport
      parentRoute: typeof AppBoardSessionsRoute
    }
    '/app/board/rankings/': {
      id: '/app/board/rankings/'
      path: '/'
      fullPath: '/app/board/rankings/'
      preLoaderRoute: typeof AppBoardRankingsIndexRouteImport
      parentRoute: typeof AppBoardRankingsRoute
    }
    '/app/series/$slug/$tab': {
      id: '/app/series/$slug/$tab'
      path: '/$slug/$tab'
      fullPath: '/app/series/$slug/$tab'
      preLoaderRoute: typeof AppSeriesSlugTabRouteImport
      parentRoute: typeof AppSeriesRoute
    }
    '/app/mangaka/submissions/review': {
      id: '/app/mangaka/submissions/review'
      path: '/mangaka/submissions/review'
      fullPath: '/app/mangaka/submissions/review'
      preLoaderRoute: typeof AppMangakaSubmissionsReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editor/review/$submissionId': {
      id: '/app/editor/review/$submissionId'
      path: '/$submissionId'
      fullPath: '/app/editor/review/$submissionId'
      preLoaderRoute: typeof AppEditorReviewSubmissionIdRouteImport
      parentRoute: typeof AppEditorReviewRoute
    }
    '/app/editor/proposals/$proposalId': {
      id: '/app/editor/proposals/$proposalId'
      path: '/proposals/$proposalId'
      fullPath: '/app/editor/proposals/$proposalId'
      preLoaderRoute: typeof AppEditorProposalsProposalIdRouteImport
      parentRoute: typeof AppEditorRoute
    }
    '/app/board/sessions/new': {
      id: '/app/board/sessions/new'
      path: '/new'
      fullPath: '/app/board/sessions/new'
      preLoaderRoute: typeof AppBoardSessionsNewRouteImport
      parentRoute: typeof AppBoardSessionsRoute
    }
    '/app/board/sessions/$sid': {
      id: '/app/board/sessions/$sid'
      path: '/$sid'
      fullPath: '/app/board/sessions/$sid'
      preLoaderRoute: typeof AppBoardSessionsSidRouteImport
      parentRoute: typeof AppBoardSessionsRoute
    }
    '/app/board/rankings/import': {
      id: '/app/board/rankings/import'
      path: '/import'
      fullPath: '/app/board/rankings/import'
      preLoaderRoute: typeof AppBoardRankingsImportRouteImport
      parentRoute: typeof AppBoardRankingsRoute
    }
    '/app/board/proposals/$proposalId': {
      id: '/app/board/proposals/$proposalId'
      path: '/proposals/$proposalId'
      fullPath: '/app/board/proposals/$proposalId'
      preLoaderRoute: typeof AppBoardProposalsProposalIdRouteImport
      parentRoute: typeof AppBoardRoute
    }
    '/app/mangaka/submissions/$submissionId/review': {
      id: '/app/mangaka/submissions/$submissionId/review'
      path: '/mangaka/submissions/$submissionId/review'
      fullPath: '/app/mangaka/submissions/$submissionId/review'
      preLoaderRoute: typeof AppMangakaSubmissionsSubmissionIdReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editor/storyboards/$storyboardId/review': {
      id: '/app/editor/storyboards/$storyboardId/review'
      path: '/storyboards/$storyboardId/review'
      fullPath: '/app/editor/storyboards/$storyboardId/review'
      preLoaderRoute: typeof AppEditorStoryboardsStoryboardIdReviewRouteImport
      parentRoute: typeof AppEditorRoute
    }
    '/app/editor/series/$seriesId/studio': {
      id: '/app/editor/series/$seriesId/studio'
      path: '/$seriesId/studio'
      fullPath: '/app/editor/series/$seriesId/studio'
      preLoaderRoute: typeof AppEditorSeriesSeriesIdStudioRouteImport
      parentRoute: typeof AppEditorSeriesRoute
    }
    '/app/editor/chapters/$chapterId/review': {
      id: '/app/editor/chapters/$chapterId/review'
      path: '/chapters/$chapterId/review'
      fullPath: '/app/editor/chapters/$chapterId/review'
      preLoaderRoute: typeof AppEditorChaptersChapterIdReviewRouteImport
      parentRoute: typeof AppEditorRoute
    }
    '/app/editor/chapters/$chapterId/annotate': {
      id: '/app/editor/chapters/$chapterId/annotate'
      path: '/chapters/$chapterId/annotate'
      fullPath: '/app/editor/chapters/$chapterId/annotate'
      preLoaderRoute: typeof AppEditorChaptersChapterIdAnnotateRouteImport
      parentRoute: typeof AppEditorRoute
    }
    '/app/assistant/tasks/$taskId/studio': {
      id: '/app/assistant/tasks/$taskId/studio'
      path: '/$taskId/studio'
      fullPath: '/app/assistant/tasks/$taskId/studio'
      preLoaderRoute: typeof AppAssistantTasksTaskIdStudioRouteImport
      parentRoute: typeof AppAssistantTasksRoute
    }
    '/app/assistant/series/$seriesId/studio': {
      id: '/app/assistant/series/$seriesId/studio'
      path: '/series/$seriesId/studio'
      fullPath: '/app/assistant/series/$seriesId/studio'
      preLoaderRoute: typeof AppAssistantSeriesSeriesIdStudioRouteImport
      parentRoute: typeof AppAssistantRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAdminNotificationsRoute: typeof AppAdminNotificationsRoute
  AppAdminRatesRoute: typeof AppAdminRatesRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAdminNotificationsRoute: AppAdminNotificationsRoute,
  AppAdminRatesRoute: AppAdminRatesRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppAssistantTasksRouteChildren {
  AppAssistantTasksTaskIdStudioRoute: typeof AppAssistantTasksTaskIdStudioRoute
}

const AppAssistantTasksRouteChildren: AppAssistantTasksRouteChildren = {
  AppAssistantTasksTaskIdStudioRoute: AppAssistantTasksTaskIdStudioRoute,
}

const AppAssistantTasksRouteWithChildren =
  AppAssistantTasksRoute._addFileChildren(AppAssistantTasksRouteChildren)

interface AppAssistantRouteChildren {
  AppAssistantDashboardRoute: typeof AppAssistantDashboardRoute
  AppAssistantEarningsRoute: typeof AppAssistantEarningsRoute
  AppAssistantNotificationsRoute: typeof AppAssistantNotificationsRoute
  AppAssistantSubmissionsRoute: typeof AppAssistantSubmissionsRoute
  AppAssistantTasksRoute: typeof AppAssistantTasksRouteWithChildren
  AppAssistantSeriesSeriesIdStudioRoute: typeof AppAssistantSeriesSeriesIdStudioRoute
}

const AppAssistantRouteChildren: AppAssistantRouteChildren = {
  AppAssistantDashboardRoute: AppAssistantDashboardRoute,
  AppAssistantEarningsRoute: AppAssistantEarningsRoute,
  AppAssistantNotificationsRoute: AppAssistantNotificationsRoute,
  AppAssistantSubmissionsRoute: AppAssistantSubmissionsRoute,
  AppAssistantTasksRoute: AppAssistantTasksRouteWithChildren,
  AppAssistantSeriesSeriesIdStudioRoute: AppAssistantSeriesSeriesIdStudioRoute,
}

const AppAssistantRouteWithChildren = AppAssistantRoute._addFileChildren(
  AppAssistantRouteChildren,
)

interface AppBoardRankingsRouteChildren {
  AppBoardRankingsImportRoute: typeof AppBoardRankingsImportRoute
  AppBoardRankingsIndexRoute: typeof AppBoardRankingsIndexRoute
}

const AppBoardRankingsRouteChildren: AppBoardRankingsRouteChildren = {
  AppBoardRankingsImportRoute: AppBoardRankingsImportRoute,
  AppBoardRankingsIndexRoute: AppBoardRankingsIndexRoute,
}

const AppBoardRankingsRouteWithChildren =
  AppBoardRankingsRoute._addFileChildren(AppBoardRankingsRouteChildren)

interface AppBoardSessionsRouteChildren {
  AppBoardSessionsSidRoute: typeof AppBoardSessionsSidRoute
  AppBoardSessionsNewRoute: typeof AppBoardSessionsNewRoute
  AppBoardSessionsIndexRoute: typeof AppBoardSessionsIndexRoute
}

const AppBoardSessionsRouteChildren: AppBoardSessionsRouteChildren = {
  AppBoardSessionsSidRoute: AppBoardSessionsSidRoute,
  AppBoardSessionsNewRoute: AppBoardSessionsNewRoute,
  AppBoardSessionsIndexRoute: AppBoardSessionsIndexRoute,
}

const AppBoardSessionsRouteWithChildren =
  AppBoardSessionsRoute._addFileChildren(AppBoardSessionsRouteChildren)

interface AppBoardRouteChildren {
  AppBoardIdRoute: typeof AppBoardIdRoute
  AppBoardAtRiskRoute: typeof AppBoardAtRiskRoute
  AppBoardDashboardRoute: typeof AppBoardDashboardRoute
  AppBoardDecisionsRoute: typeof AppBoardDecisionsRoute
  AppBoardNotificationsRoute: typeof AppBoardNotificationsRoute
  AppBoardQueueRoute: typeof AppBoardQueueRoute
  AppBoardRankingsRoute: typeof AppBoardRankingsRouteWithChildren
  AppBoardSessionsRoute: typeof AppBoardSessionsRouteWithChildren
  AppBoardIndexRoute: typeof AppBoardIndexRoute
  AppBoardProposalsProposalIdRoute: typeof AppBoardProposalsProposalIdRoute
}

const AppBoardRouteChildren: AppBoardRouteChildren = {
  AppBoardIdRoute: AppBoardIdRoute,
  AppBoardAtRiskRoute: AppBoardAtRiskRoute,
  AppBoardDashboardRoute: AppBoardDashboardRoute,
  AppBoardDecisionsRoute: AppBoardDecisionsRoute,
  AppBoardNotificationsRoute: AppBoardNotificationsRoute,
  AppBoardQueueRoute: AppBoardQueueRoute,
  AppBoardRankingsRoute: AppBoardRankingsRouteWithChildren,
  AppBoardSessionsRoute: AppBoardSessionsRouteWithChildren,
  AppBoardIndexRoute: AppBoardIndexRoute,
  AppBoardProposalsProposalIdRoute: AppBoardProposalsProposalIdRoute,
}

const AppBoardRouteWithChildren = AppBoardRoute._addFileChildren(
  AppBoardRouteChildren,
)

interface AppEditorReviewRouteChildren {
  AppEditorReviewSubmissionIdRoute: typeof AppEditorReviewSubmissionIdRoute
  AppEditorReviewIndexRoute: typeof AppEditorReviewIndexRoute
}

const AppEditorReviewRouteChildren: AppEditorReviewRouteChildren = {
  AppEditorReviewSubmissionIdRoute: AppEditorReviewSubmissionIdRoute,
  AppEditorReviewIndexRoute: AppEditorReviewIndexRoute,
}

const AppEditorReviewRouteWithChildren = AppEditorReviewRoute._addFileChildren(
  AppEditorReviewRouteChildren,
)

interface AppEditorSeriesRouteChildren {
  AppEditorSeriesIndexRoute: typeof AppEditorSeriesIndexRoute
  AppEditorSeriesSeriesIdStudioRoute: typeof AppEditorSeriesSeriesIdStudioRoute
}

const AppEditorSeriesRouteChildren: AppEditorSeriesRouteChildren = {
  AppEditorSeriesIndexRoute: AppEditorSeriesIndexRoute,
  AppEditorSeriesSeriesIdStudioRoute: AppEditorSeriesSeriesIdStudioRoute,
}

const AppEditorSeriesRouteWithChildren = AppEditorSeriesRoute._addFileChildren(
  AppEditorSeriesRouteChildren,
)

interface AppEditorRouteChildren {
  AppEditorDashboardRoute: typeof AppEditorDashboardRoute
  AppEditorNotificationsRoute: typeof AppEditorNotificationsRoute
  AppEditorPublicationsRoute: typeof AppEditorPublicationsRoute
  AppEditorReviewRoute: typeof AppEditorReviewRouteWithChildren
  AppEditorSeriesRoute: typeof AppEditorSeriesRouteWithChildren
  AppEditorProposalsProposalIdRoute: typeof AppEditorProposalsProposalIdRoute
  AppEditorChaptersChapterIdAnnotateRoute: typeof AppEditorChaptersChapterIdAnnotateRoute
  AppEditorChaptersChapterIdReviewRoute: typeof AppEditorChaptersChapterIdReviewRoute
  AppEditorStoryboardsStoryboardIdReviewRoute: typeof AppEditorStoryboardsStoryboardIdReviewRoute
}

const AppEditorRouteChildren: AppEditorRouteChildren = {
  AppEditorDashboardRoute: AppEditorDashboardRoute,
  AppEditorNotificationsRoute: AppEditorNotificationsRoute,
  AppEditorPublicationsRoute: AppEditorPublicationsRoute,
  AppEditorReviewRoute: AppEditorReviewRouteWithChildren,
  AppEditorSeriesRoute: AppEditorSeriesRouteWithChildren,
  AppEditorProposalsProposalIdRoute: AppEditorProposalsProposalIdRoute,
  AppEditorChaptersChapterIdAnnotateRoute:
    AppEditorChaptersChapterIdAnnotateRoute,
  AppEditorChaptersChapterIdReviewRoute: AppEditorChaptersChapterIdReviewRoute,
  AppEditorStoryboardsStoryboardIdReviewRoute:
    AppEditorStoryboardsStoryboardIdReviewRoute,
}

const AppEditorRouteWithChildren = AppEditorRoute._addFileChildren(
  AppEditorRouteChildren,
)

interface AppProposalsRouteChildren {
  AppProposalsProposalIdRoute: typeof AppProposalsProposalIdRoute
  AppProposalsNewRoute: typeof AppProposalsNewRoute
  AppProposalsIndexRoute: typeof AppProposalsIndexRoute
}

const AppProposalsRouteChildren: AppProposalsRouteChildren = {
  AppProposalsProposalIdRoute: AppProposalsProposalIdRoute,
  AppProposalsNewRoute: AppProposalsNewRoute,
  AppProposalsIndexRoute: AppProposalsIndexRoute,
}

const AppProposalsRouteWithChildren = AppProposalsRoute._addFileChildren(
  AppProposalsRouteChildren,
)

interface AppSeriesRouteChildren {
  AppSeriesIndexRoute: typeof AppSeriesIndexRoute
  AppSeriesSlugTabRoute: typeof AppSeriesSlugTabRoute
}

const AppSeriesRouteChildren: AppSeriesRouteChildren = {
  AppSeriesIndexRoute: AppSeriesIndexRoute,
  AppSeriesSlugTabRoute: AppSeriesSlugTabRoute,
}

const AppSeriesRouteWithChildren = AppSeriesRoute._addFileChildren(
  AppSeriesRouteChildren,
)

interface AppSubmissionsRouteChildren {
  AppSubmissionsIdRoute: typeof AppSubmissionsIdRoute
  AppSubmissionsNewRoute: typeof AppSubmissionsNewRoute
  AppSubmissionsIndexRoute: typeof AppSubmissionsIndexRoute
}

const AppSubmissionsRouteChildren: AppSubmissionsRouteChildren = {
  AppSubmissionsIdRoute: AppSubmissionsIdRoute,
  AppSubmissionsNewRoute: AppSubmissionsNewRoute,
  AppSubmissionsIndexRoute: AppSubmissionsIndexRoute,
}

const AppSubmissionsRouteWithChildren = AppSubmissionsRoute._addFileChildren(
  AppSubmissionsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAssistantRoute: typeof AppAssistantRouteWithChildren
  AppBoardRoute: typeof AppBoardRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppEditorRoute: typeof AppEditorRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProposalsRoute: typeof AppProposalsRouteWithChildren
  AppRankingsRoute: typeof AppRankingsRoute
  AppSeriesRoute: typeof AppSeriesRouteWithChildren
  AppSubmissionsRoute: typeof AppSubmissionsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppMangakaSubmissionsReviewRoute: typeof AppMangakaSubmissionsReviewRoute
  AppMangakaSubmissionsSubmissionIdReviewRoute: typeof AppMangakaSubmissionsSubmissionIdReviewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAssistantRoute: AppAssistantRouteWithChildren,
  AppBoardRoute: AppBoardRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppEditorRoute: AppEditorRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProposalsRoute: AppProposalsRouteWithChildren,
  AppRankingsRoute: AppRankingsRoute,
  AppSeriesRoute: AppSeriesRouteWithChildren,
  AppSubmissionsRoute: AppSubmissionsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppMangakaSubmissionsReviewRoute: AppMangakaSubmissionsReviewRoute,
  AppMangakaSubmissionsSubmissionIdReviewRoute:
    AppMangakaSubmissionsSubmissionIdReviewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ReadSlugRouteChildren {
  ReadSlugChapterRoute: typeof ReadSlugChapterRoute
  ReadSlugIndexRoute: typeof ReadSlugIndexRoute
}

const ReadSlugRouteChildren: ReadSlugRouteChildren = {
  ReadSlugChapterRoute: ReadSlugChapterRoute,
  ReadSlugIndexRoute: ReadSlugIndexRoute,
}

const ReadSlugRouteWithChildren = ReadSlugRoute._addFileChildren(
  ReadSlugRouteChildren,
)

interface ReadRouteChildren {
  ReadSlugRoute: typeof ReadSlugRouteWithChildren
  ReadIndexRoute: typeof ReadIndexRoute
}

const ReadRouteChildren: ReadRouteChildren = {
  ReadSlugRoute: ReadSlugRouteWithChildren,
  ReadIndexRoute: ReadIndexRoute,
}

const ReadRouteWithChildren = ReadRoute._addFileChildren(ReadRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ReadRoute: ReadRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
