import { ActionItemList, AtRiskBadge, DecisionBadge, RankingTable, ReviewDecisionBar, StatusBadge, VoteCard } from "@/shared/components/domain"
import { MFEmptyState } from "@/shared/components/feedback/MFEmptyState"
import { MFErrorState } from "@/shared/components/feedback/MFErrorState"
import { MFBadge, MFButton, MFCard, MFTable } from "@/shared/components/ui"
import type { AtRiskDecisionValue, BoardQueueItem, BoardVoteValue } from "../api/board.api"
import { boardColumns, boardDecisionStatusUI, rankingStatusUI } from "../utils/board-page.mappers"
import type { BoardQueueRow } from "../utils/board-page.mappers"
import type { RankingTableRow, VoteCardOption } from "@/shared/components/domain"

export function BoardStatePreview() {
  return (
    <MFCard>
      <div className="flex flex-wrap items-start justify-between gap-md"><div><h2 className="text-title-lg text-on-surface">Board states</h2><p className="mt-xs text-body-md text-on-surface-muted">Queue, ranking, and at-risk actions are backend-owned. The UI shows explicit workflow actions only.</p></div><MFBadge tone="success" size="md">API-backed</MFBadge></div>
      <div className="mt-lg grid gap-md xl:grid-cols-4">
        <div className="rounded-3xl bg-surface-low p-lg" aria-label="Loading board preview"><div className="h-4 w-32 rounded-full bg-surface-container" /><div className="mt-md space-y-sm"><div className="h-3 rounded-full bg-surface-container" /><div className="h-3 w-2/3 rounded-full bg-surface-container" /><div className="h-3 w-1/2 rounded-full bg-surface-container" /></div><p className="mt-md text-label-sm text-on-surface-muted">Loading preview</p></div>
        <MFEmptyState icon="how_to_vote" title="No Board items" description="The Board queue stays empty until Series reach BOARD_REVIEW or AT_RISK." />
        <MFErrorState title="Could not load Board queue" description="Recoverable API error preview." onRetry={() => undefined} />
        <div className="rounded-3xl bg-surface-low p-lg"><div className="flex flex-wrap gap-sm"><DecisionBadge status="PENDING" /><DecisionBadge status="TIE_BREAK_REQUIRED" /><StatusBadge status="IMPORTED" mapping={rankingStatusUI} /><AtRiskBadge status="AT_RISK" /></div><p className="mt-md text-body-md text-on-surface">Board workflow states stay text-visible and do not rely on color alone.</p></div>
      </div>
    </MFCard>
  )
}

export function BoardQueuePanel({ boardActions, boardQueueRows, loading, error, onRetry }: { boardActions: any[]; boardQueueRows: BoardQueueRow[]; loading: boolean; error: string; onRetry: () => void }) {
  if (loading) return <PageLoading />
  if (error) return <PageError error={error} onRetry={onRetry} />
  return <section className="grid gap-lg xl:grid-cols-[24rem_minmax(0,1fr)]"><div><h2 className="mb-md text-title-lg text-on-surface">Board actions</h2><ActionItemList items={boardActions} statusMapping={boardDecisionStatusUI} /></div><div><h2 className="mb-md text-title-lg text-on-surface">Approval queue</h2><MFTable caption="Board approval queue" rows={boardQueueRows} columns={boardColumns} getRowKey={(row) => row.id} emptyTitle="No Board queue items" emptyDescription="Board records appear here when backend grants access and Series reach BOARD_REVIEW or AT_RISK." /></div></section>
}

function PageLoading() { return <MFCard><div className="h-40 rounded-3xl bg-surface-low" /></MFCard> }
function PageError({ error, onRetry }: { error: string; onRetry: () => void }) { return <MFErrorState title="Could not load Board queue" description={error} onRetry={onRetry} /> }

export function BoardVotePanel({ firstBoardSeries, activeSeriesId, votePreview, voteOptions, finalizeVote, tieBreak }: { firstBoardSeries: BoardQueueItem | null; activeSeriesId: string | null; votePreview: string; voteOptions: VoteCardOption[]; finalizeVote: () => Promise<void>; tieBreak: (value: BoardVoteValue) => Promise<void> }) {
  return <section className="grid gap-lg xl:grid-cols-[minmax(0,1fr)_24rem]"><div className="space-y-lg"><VoteCard title="Series approval vote" description={firstBoardSeries ? `Vote on ${firstBoardSeries.seriesTitle}.` : "No Series in BOARD_REVIEW."} options={voteOptions} resultLabel={firstBoardSeries?.seriesStatus ?? "No target"} totalVotesLabel={firstBoardSeries ? "Live summary" : "No live series"} tieBreakRequired={votePreview.includes("Tie-break")} boardChairNote="Board Chair tie-break remains backend-authorized only." disabled={!firstBoardSeries || activeSeriesId === firstBoardSeries.id} loadingOptionId={null} /><MFCard><div className="flex flex-wrap items-start justify-between gap-md"><div><h2 className="text-title-lg text-on-surface">Board workflow actions</h2><p className="mt-xs text-body-md text-on-surface-muted">Finalize and tie-break call backend endpoints.</p></div><MFBadge tone="neutral" size="md">API-backed</MFBadge></div><div className="mt-lg flex flex-wrap gap-sm"><MFButton type="button" variant="outline" size="sm" onClick={() => void finalizeVote()} disabled={!firstBoardSeries || Boolean(activeSeriesId)}>Finalize decision</MFButton><MFButton type="button" variant="outline" size="sm" onClick={() => void tieBreak("APPROVE")} disabled={!firstBoardSeries || Boolean(activeSeriesId)}>Tie-break approve</MFButton><MFButton type="button" variant="outline" size="sm" onClick={() => void tieBreak("REJECT")} disabled={!firstBoardSeries || Boolean(activeSeriesId)}>Tie-break reject</MFButton><MFButton type="button" variant="outline" size="sm" onClick={() => void tieBreak("NEEDS_REVISION")} disabled={!firstBoardSeries || Boolean(activeSeriesId)}>Tie-break revision</MFButton></div><p className="mt-lg rounded-2xl bg-surface-low p-lg text-body-md text-on-surface">{votePreview}</p></MFCard></div><div className="space-y-lg"><MFCard><h2 className="text-title-lg text-on-surface">Decision status</h2><p className="mt-xs text-body-md text-on-surface-muted">Decision badges stay display-only summaries of backend state.</p><div className="mt-lg flex flex-wrap gap-sm"><DecisionBadge status="PENDING" size="md" /><DecisionBadge status="TIE_BREAK_REQUIRED" size="md" /><DecisionBadge status="FINALIZED" size="md" /></div></MFCard><MFCard><h2 className="text-title-lg text-on-surface">At-risk status</h2><p className="mt-xs text-body-md text-on-surface-muted">Manual Board at-risk outcomes stay text-visible and use explicit confirmation.</p><div className="mt-lg flex flex-wrap gap-sm"><AtRiskBadge status="WARNING" size="md" /><AtRiskBadge status="AT_RISK" size="md" /><AtRiskBadge status="CONTINUE" size="md" /></div></MFCard></div></section>
}

export function BoardRankingPanel({ rankingRows, rankingLoading, rankingForm, setRankingForm, rankingMessage, submitRankingImport, finalizeTopRanking }: { rankingRows: RankingTableRow[]; rankingLoading: boolean; rankingForm: { period: string; seriesId: string; voteCount: string; readerScore: string }; setRankingForm: React.Dispatch<React.SetStateAction<{ period: string; seriesId: string; voteCount: string; readerScore: string }>>; rankingMessage: string; submitRankingImport: () => Promise<void>; finalizeTopRanking: () => Promise<void> }) {
  return <div className="space-y-md"><div className="flex flex-wrap items-center justify-between gap-md"><h2 className="text-title-lg text-on-surface">Ranking import</h2><MFBadge tone="success" size="md">API-backed</MFBadge></div><RankingTable rows={rankingRows} loading={rankingLoading} /><MFCard><div className="grid gap-md md:grid-cols-4"><input className="rounded-xl border border-outline-variant bg-surface-lowest px-md py-sm text-body-md" placeholder="Period e.g. 2026-06" value={rankingForm.period} onChange={(event) => setRankingForm((current) => ({ ...current, period: event.target.value }))} /><input className="rounded-xl border border-outline-variant bg-surface-lowest px-md py-sm text-body-md" placeholder="Series ID" value={rankingForm.seriesId} onChange={(event) => setRankingForm((current) => ({ ...current, seriesId: event.target.value }))} /><input className="rounded-xl border border-outline-variant bg-surface-lowest px-md py-sm text-body-md" placeholder="Vote count" inputMode="numeric" value={rankingForm.voteCount} onChange={(event) => setRankingForm((current) => ({ ...current, voteCount: event.target.value }))} /><input className="rounded-xl border border-outline-variant bg-surface-lowest px-md py-sm text-body-md" placeholder="Reader score 1-10" inputMode="decimal" value={rankingForm.readerScore} onChange={(event) => setRankingForm((current) => ({ ...current, readerScore: event.target.value }))} /></div><div className="mt-md flex flex-wrap gap-sm"><MFButton type="button" size="sm" onClick={() => void submitRankingImport()} disabled={!rankingForm.period || !rankingForm.seriesId || !rankingForm.voteCount || !rankingForm.readerScore}>Import ranking</MFButton><MFButton type="button" variant="outline" size="sm" onClick={() => void finalizeTopRanking()}>Finalize top imported row</MFButton></div><p className="mt-md rounded-2xl bg-surface-low p-md text-body-md text-on-surface">{rankingMessage}</p></MFCard></div>
}

export function BoardAtRiskPanel({ firstAtRiskSeries, atRiskPreview, submitAtRiskDecision }: { firstAtRiskSeries: BoardQueueItem | null; atRiskPreview: string; submitAtRiskDecision: (decision: AtRiskDecisionValue, note: string) => Promise<void> }) {
  return <div className="space-y-lg"><ReviewDecisionBar title="At-risk decision" description={firstAtRiskSeries ? `Manual Board action for ${firstAtRiskSeries.seriesTitle}.` : "No AT_RISK series is waiting for a Board at-risk decision."} approveLabel="Continue production" requestRevisionLabel="Request plan" rejectLabel="Cancel series" rejectConfirmationTitle="Cancel this at-risk series?" rejectConfirmationDescription="This sends a real backend Board cancellation decision and moves the Series to CANCELLED." onApprove={() => void submitAtRiskDecision("CONTINUE", "Continue production after Board at-risk review.")} onRequestRevision={() => void submitAtRiskDecision("REQUEST_IMPROVEMENT_PLAN", "Board requests an improvement plan before continuing.")} onReject={() => void submitAtRiskDecision("CANCEL", "Board manually cancelled this AT_RISK series.")} /><MFCard><div className="flex flex-wrap items-start justify-between gap-md"><div><h2 className="text-title-lg text-on-surface">At-risk decision result</h2><p className="mt-xs text-body-md text-on-surface-muted">Backend response updates this summary after confirmation.</p></div><MFBadge tone="neutral" size="md">Manual Board action</MFBadge></div><p className="mt-lg rounded-2xl bg-surface-low p-lg text-body-md text-on-surface">{atRiskPreview}</p></MFCard></div>
}
